// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: review.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "review.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* Review_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Review_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_review_2eproto() {
  protobuf_AddDesc_review_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "review.proto");
  GOOGLE_CHECK(file != NULL);
  Review_descriptor_ = file->message_type(0);
  static const int Review_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Review, reviewer_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Review, rating_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Review, object_properties_),
  };
  Review_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Review_descriptor_,
      Review::default_instance_,
      Review_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Review, _has_bits_[0]),
      -1,
      -1,
      sizeof(Review),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Review, _internal_metadata_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_review_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Review_descriptor_, &Review::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_review_2eproto() {
  delete Review::default_instance_;
  delete Review_reflection_;
}

void protobuf_AddDesc_review_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::pjcore::protobuf_AddDesc_pjcore_2fjson_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\014review.proto\032\021pjcore/json.proto\"a\n\006Rev"
    "iew\022\020\n\010reviewer\030\001 \001(\t\022\016\n\006rating\030\002 \001(\001\0225\n"
    "\021object_properties\030\003 \003(\0132\032.pjcore.JsonVa"
    "lue.Property", 132);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "review.proto", &protobuf_RegisterTypes);
  Review::default_instance_ = new Review();
  Review::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_review_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_review_2eproto {
  StaticDescriptorInitializer_review_2eproto() {
    protobuf_AddDesc_review_2eproto();
  }
} static_descriptor_initializer_review_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#ifndef _MSC_VER
const int Review::kReviewerFieldNumber;
const int Review::kRatingFieldNumber;
const int Review::kObjectPropertiesFieldNumber;
#endif  // !_MSC_VER

Review::Review()
  : ::google::protobuf::Message() , _internal_metadata_(NULL)  {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Review)
}

void Review::InitAsDefaultInstance() {
}

Review::Review(const Review& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Review)
}

void Review::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  reviewer_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  rating_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Review::~Review() {
  // @@protoc_insertion_point(destructor:Review)
  SharedDtor();
}

void Review::SharedDtor() {
  reviewer_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void Review::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Review::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Review_descriptor_;
}

const Review& Review::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_review_2eproto();
  return *default_instance_;
}

Review* Review::default_instance_ = NULL;

Review* Review::New(::google::protobuf::Arena* arena) const {
  Review* n = new Review;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Review::Clear() {
  if (_has_bits_[0 / 32] & 3) {
    if (has_reviewer()) {
      reviewer_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    rating_ = 0;
  }
  object_properties_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool Review::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Review)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string reviewer = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_reviewer()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->reviewer().data(), this->reviewer().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "Review.reviewer");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(17)) goto parse_rating;
        break;
      }

      // optional double rating = 2;
      case 2: {
        if (tag == 17) {
         parse_rating:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &rating_)));
          set_has_rating();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_object_properties;
        break;
      }

      // repeated .pjcore.JsonValue.Property object_properties = 3;
      case 3: {
        if (tag == 26) {
         parse_object_properties:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_object_properties()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_object_properties;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Review)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Review)
  return false;
#undef DO_
}

void Review::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Review)
  // optional string reviewer = 1;
  if (has_reviewer()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->reviewer().data(), this->reviewer().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "Review.reviewer");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->reviewer(), output);
  }

  // optional double rating = 2;
  if (has_rating()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->rating(), output);
  }

  // repeated .pjcore.JsonValue.Property object_properties = 3;
  for (unsigned int i = 0, n = this->object_properties_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->object_properties(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:Review)
}

::google::protobuf::uint8* Review::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Review)
  // optional string reviewer = 1;
  if (has_reviewer()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->reviewer().data(), this->reviewer().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "Review.reviewer");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->reviewer(), target);
  }

  // optional double rating = 2;
  if (has_rating()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->rating(), target);
  }

  // repeated .pjcore.JsonValue.Property object_properties = 3;
  for (unsigned int i = 0, n = this->object_properties_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->object_properties(i), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Review)
  return target;
}

int Review::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & 3) {
    // optional string reviewer = 1;
    if (has_reviewer()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->reviewer());
    }

    // optional double rating = 2;
    if (has_rating()) {
      total_size += 1 + 8;
    }

  }
  // repeated .pjcore.JsonValue.Property object_properties = 3;
  total_size += 1 * this->object_properties_size();
  for (int i = 0; i < this->object_properties_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->object_properties(i));
  }

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Review::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const Review* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Review*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Review::MergeFrom(const Review& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  object_properties_.MergeFrom(from.object_properties_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_reviewer()) {
      set_has_reviewer();
      reviewer_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.reviewer_);
    }
    if (from.has_rating()) {
      set_rating(from.rating());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void Review::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Review::CopyFrom(const Review& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Review::IsInitialized() const {

  return true;
}

void Review::Swap(Review* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Review::InternalSwap(Review* other) {
  reviewer_.Swap(&other->reviewer_);
  std::swap(rating_, other->rating_);
  object_properties_.UnsafeArenaSwap(&other->object_properties_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Review::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Review_descriptor_;
  metadata.reflection = Review_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
