// This file was GENERATED by command:
//     pump.py make_json_value_pump.h.pump
// DO NOT EDIT BY HAND!!!

// JSON [de]serialization for protobuf + embedded HTTP server and client in C++.
// Copyright (C) 2014 http://protojson.com/
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program; if not, write to the Free Software Foundation, Inc.,
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

#ifndef PJCORE_MAKE_JSON_VALUE_PUMP_H_
#define PJCORE_MAKE_JSON_VALUE_PUMP_H_

#include <string>

#include "pjcore/make_json_value.h"

namespace pjcore {

template <typename Value1>
JsonValue MakeJsonObject(StringPiece name_1, Value1 value_1) {
  JsonValue json_object = MakeJsonObject();
  *json_object.add_object_properties() = MakeJsonProperty(name_1, value_1);
  return json_object;
}


template <typename Value1, typename Value2>
JsonValue MakeJsonObject(StringPiece name_1, Value1 value_1,
    StringPiece name_2, Value2 value_2) {
  JsonValue json_object = MakeJsonObject();
  *json_object.add_object_properties() = MakeJsonProperty(name_1, value_1);
  *json_object.add_object_properties() = MakeJsonProperty(name_2, value_2);
  return json_object;
}


template <typename Value1, typename Value2, typename Value3>
JsonValue MakeJsonObject(StringPiece name_1, Value1 value_1,
    StringPiece name_2, Value2 value_2, StringPiece name_3, Value3 value_3) {
  JsonValue json_object = MakeJsonObject();
  *json_object.add_object_properties() = MakeJsonProperty(name_1, value_1);
  *json_object.add_object_properties() = MakeJsonProperty(name_2, value_2);
  *json_object.add_object_properties() = MakeJsonProperty(name_3, value_3);
  return json_object;
}


template <typename Value1, typename Value2, typename Value3, typename Value4>
JsonValue MakeJsonObject(StringPiece name_1, Value1 value_1,
    StringPiece name_2, Value2 value_2, StringPiece name_3, Value3 value_3,
    StringPiece name_4, Value4 value_4) {
  JsonValue json_object = MakeJsonObject();
  *json_object.add_object_properties() = MakeJsonProperty(name_1, value_1);
  *json_object.add_object_properties() = MakeJsonProperty(name_2, value_2);
  *json_object.add_object_properties() = MakeJsonProperty(name_3, value_3);
  *json_object.add_object_properties() = MakeJsonProperty(name_4, value_4);
  return json_object;
}


template <typename Value1, typename Value2, typename Value3, typename Value4,
    typename Value5>
JsonValue MakeJsonObject(StringPiece name_1, Value1 value_1,
    StringPiece name_2, Value2 value_2, StringPiece name_3, Value3 value_3,
    StringPiece name_4, Value4 value_4, StringPiece name_5, Value5 value_5) {
  JsonValue json_object = MakeJsonObject();
  *json_object.add_object_properties() = MakeJsonProperty(name_1, value_1);
  *json_object.add_object_properties() = MakeJsonProperty(name_2, value_2);
  *json_object.add_object_properties() = MakeJsonProperty(name_3, value_3);
  *json_object.add_object_properties() = MakeJsonProperty(name_4, value_4);
  *json_object.add_object_properties() = MakeJsonProperty(name_5, value_5);
  return json_object;
}


template <typename Value1, typename Value2, typename Value3, typename Value4,
    typename Value5, typename Value6>
JsonValue MakeJsonObject(StringPiece name_1, Value1 value_1,
    StringPiece name_2, Value2 value_2, StringPiece name_3, Value3 value_3,
    StringPiece name_4, Value4 value_4, StringPiece name_5, Value5 value_5,
    StringPiece name_6, Value6 value_6) {
  JsonValue json_object = MakeJsonObject();
  *json_object.add_object_properties() = MakeJsonProperty(name_1, value_1);
  *json_object.add_object_properties() = MakeJsonProperty(name_2, value_2);
  *json_object.add_object_properties() = MakeJsonProperty(name_3, value_3);
  *json_object.add_object_properties() = MakeJsonProperty(name_4, value_4);
  *json_object.add_object_properties() = MakeJsonProperty(name_5, value_5);
  *json_object.add_object_properties() = MakeJsonProperty(name_6, value_6);
  return json_object;
}


template <typename Value1, typename Value2, typename Value3, typename Value4,
    typename Value5, typename Value6, typename Value7>
JsonValue MakeJsonObject(StringPiece name_1, Value1 value_1,
    StringPiece name_2, Value2 value_2, StringPiece name_3, Value3 value_3,
    StringPiece name_4, Value4 value_4, StringPiece name_5, Value5 value_5,
    StringPiece name_6, Value6 value_6, StringPiece name_7, Value7 value_7) {
  JsonValue json_object = MakeJsonObject();
  *json_object.add_object_properties() = MakeJsonProperty(name_1, value_1);
  *json_object.add_object_properties() = MakeJsonProperty(name_2, value_2);
  *json_object.add_object_properties() = MakeJsonProperty(name_3, value_3);
  *json_object.add_object_properties() = MakeJsonProperty(name_4, value_4);
  *json_object.add_object_properties() = MakeJsonProperty(name_5, value_5);
  *json_object.add_object_properties() = MakeJsonProperty(name_6, value_6);
  *json_object.add_object_properties() = MakeJsonProperty(name_7, value_7);
  return json_object;
}


template <typename Value1, typename Value2, typename Value3, typename Value4,
    typename Value5, typename Value6, typename Value7, typename Value8>
JsonValue MakeJsonObject(StringPiece name_1, Value1 value_1,
    StringPiece name_2, Value2 value_2, StringPiece name_3, Value3 value_3,
    StringPiece name_4, Value4 value_4, StringPiece name_5, Value5 value_5,
    StringPiece name_6, Value6 value_6, StringPiece name_7, Value7 value_7,
    StringPiece name_8, Value8 value_8) {
  JsonValue json_object = MakeJsonObject();
  *json_object.add_object_properties() = MakeJsonProperty(name_1, value_1);
  *json_object.add_object_properties() = MakeJsonProperty(name_2, value_2);
  *json_object.add_object_properties() = MakeJsonProperty(name_3, value_3);
  *json_object.add_object_properties() = MakeJsonProperty(name_4, value_4);
  *json_object.add_object_properties() = MakeJsonProperty(name_5, value_5);
  *json_object.add_object_properties() = MakeJsonProperty(name_6, value_6);
  *json_object.add_object_properties() = MakeJsonProperty(name_7, value_7);
  *json_object.add_object_properties() = MakeJsonProperty(name_8, value_8);
  return json_object;
}


template <typename Value1, typename Value2, typename Value3, typename Value4,
    typename Value5, typename Value6, typename Value7, typename Value8,
    typename Value9>
JsonValue MakeJsonObject(StringPiece name_1, Value1 value_1,
    StringPiece name_2, Value2 value_2, StringPiece name_3, Value3 value_3,
    StringPiece name_4, Value4 value_4, StringPiece name_5, Value5 value_5,
    StringPiece name_6, Value6 value_6, StringPiece name_7, Value7 value_7,
    StringPiece name_8, Value8 value_8, StringPiece name_9, Value9 value_9) {
  JsonValue json_object = MakeJsonObject();
  *json_object.add_object_properties() = MakeJsonProperty(name_1, value_1);
  *json_object.add_object_properties() = MakeJsonProperty(name_2, value_2);
  *json_object.add_object_properties() = MakeJsonProperty(name_3, value_3);
  *json_object.add_object_properties() = MakeJsonProperty(name_4, value_4);
  *json_object.add_object_properties() = MakeJsonProperty(name_5, value_5);
  *json_object.add_object_properties() = MakeJsonProperty(name_6, value_6);
  *json_object.add_object_properties() = MakeJsonProperty(name_7, value_7);
  *json_object.add_object_properties() = MakeJsonProperty(name_8, value_8);
  *json_object.add_object_properties() = MakeJsonProperty(name_9, value_9);
  return json_object;
}


template <typename Value1, typename Value2, typename Value3, typename Value4,
    typename Value5, typename Value6, typename Value7, typename Value8,
    typename Value9, typename Value10>
JsonValue MakeJsonObject(StringPiece name_1, Value1 value_1,
    StringPiece name_2, Value2 value_2, StringPiece name_3, Value3 value_3,
    StringPiece name_4, Value4 value_4, StringPiece name_5, Value5 value_5,
    StringPiece name_6, Value6 value_6, StringPiece name_7, Value7 value_7,
    StringPiece name_8, Value8 value_8, StringPiece name_9, Value9 value_9,
    StringPiece name_10, Value10 value_10) {
  JsonValue json_object = MakeJsonObject();
  *json_object.add_object_properties() = MakeJsonProperty(name_1, value_1);
  *json_object.add_object_properties() = MakeJsonProperty(name_2, value_2);
  *json_object.add_object_properties() = MakeJsonProperty(name_3, value_3);
  *json_object.add_object_properties() = MakeJsonProperty(name_4, value_4);
  *json_object.add_object_properties() = MakeJsonProperty(name_5, value_5);
  *json_object.add_object_properties() = MakeJsonProperty(name_6, value_6);
  *json_object.add_object_properties() = MakeJsonProperty(name_7, value_7);
  *json_object.add_object_properties() = MakeJsonProperty(name_8, value_8);
  *json_object.add_object_properties() = MakeJsonProperty(name_9, value_9);
  *json_object.add_object_properties() = MakeJsonProperty(name_10, value_10);
  return json_object;
}


template <typename Value1, typename Value2, typename Value3, typename Value4,
    typename Value5, typename Value6, typename Value7, typename Value8,
    typename Value9, typename Value10, typename Value11>
JsonValue MakeJsonObject(StringPiece name_1, Value1 value_1,
    StringPiece name_2, Value2 value_2, StringPiece name_3, Value3 value_3,
    StringPiece name_4, Value4 value_4, StringPiece name_5, Value5 value_5,
    StringPiece name_6, Value6 value_6, StringPiece name_7, Value7 value_7,
    StringPiece name_8, Value8 value_8, StringPiece name_9, Value9 value_9,
    StringPiece name_10, Value10 value_10, StringPiece name_11,
    Value11 value_11) {
  JsonValue json_object = MakeJsonObject();
  *json_object.add_object_properties() = MakeJsonProperty(name_1, value_1);
  *json_object.add_object_properties() = MakeJsonProperty(name_2, value_2);
  *json_object.add_object_properties() = MakeJsonProperty(name_3, value_3);
  *json_object.add_object_properties() = MakeJsonProperty(name_4, value_4);
  *json_object.add_object_properties() = MakeJsonProperty(name_5, value_5);
  *json_object.add_object_properties() = MakeJsonProperty(name_6, value_6);
  *json_object.add_object_properties() = MakeJsonProperty(name_7, value_7);
  *json_object.add_object_properties() = MakeJsonProperty(name_8, value_8);
  *json_object.add_object_properties() = MakeJsonProperty(name_9, value_9);
  *json_object.add_object_properties() = MakeJsonProperty(name_10, value_10);
  *json_object.add_object_properties() = MakeJsonProperty(name_11, value_11);
  return json_object;
}


template <typename Value1, typename Value2, typename Value3, typename Value4,
    typename Value5, typename Value6, typename Value7, typename Value8,
    typename Value9, typename Value10, typename Value11, typename Value12>
JsonValue MakeJsonObject(StringPiece name_1, Value1 value_1,
    StringPiece name_2, Value2 value_2, StringPiece name_3, Value3 value_3,
    StringPiece name_4, Value4 value_4, StringPiece name_5, Value5 value_5,
    StringPiece name_6, Value6 value_6, StringPiece name_7, Value7 value_7,
    StringPiece name_8, Value8 value_8, StringPiece name_9, Value9 value_9,
    StringPiece name_10, Value10 value_10, StringPiece name_11,
    Value11 value_11, StringPiece name_12, Value12 value_12) {
  JsonValue json_object = MakeJsonObject();
  *json_object.add_object_properties() = MakeJsonProperty(name_1, value_1);
  *json_object.add_object_properties() = MakeJsonProperty(name_2, value_2);
  *json_object.add_object_properties() = MakeJsonProperty(name_3, value_3);
  *json_object.add_object_properties() = MakeJsonProperty(name_4, value_4);
  *json_object.add_object_properties() = MakeJsonProperty(name_5, value_5);
  *json_object.add_object_properties() = MakeJsonProperty(name_6, value_6);
  *json_object.add_object_properties() = MakeJsonProperty(name_7, value_7);
  *json_object.add_object_properties() = MakeJsonProperty(name_8, value_8);
  *json_object.add_object_properties() = MakeJsonProperty(name_9, value_9);
  *json_object.add_object_properties() = MakeJsonProperty(name_10, value_10);
  *json_object.add_object_properties() = MakeJsonProperty(name_11, value_11);
  *json_object.add_object_properties() = MakeJsonProperty(name_12, value_12);
  return json_object;
}


template <typename Value1, typename Value2, typename Value3, typename Value4,
    typename Value5, typename Value6, typename Value7, typename Value8,
    typename Value9, typename Value10, typename Value11, typename Value12,
    typename Value13>
JsonValue MakeJsonObject(StringPiece name_1, Value1 value_1,
    StringPiece name_2, Value2 value_2, StringPiece name_3, Value3 value_3,
    StringPiece name_4, Value4 value_4, StringPiece name_5, Value5 value_5,
    StringPiece name_6, Value6 value_6, StringPiece name_7, Value7 value_7,
    StringPiece name_8, Value8 value_8, StringPiece name_9, Value9 value_9,
    StringPiece name_10, Value10 value_10, StringPiece name_11,
    Value11 value_11, StringPiece name_12, Value12 value_12,
    StringPiece name_13, Value13 value_13) {
  JsonValue json_object = MakeJsonObject();
  *json_object.add_object_properties() = MakeJsonProperty(name_1, value_1);
  *json_object.add_object_properties() = MakeJsonProperty(name_2, value_2);
  *json_object.add_object_properties() = MakeJsonProperty(name_3, value_3);
  *json_object.add_object_properties() = MakeJsonProperty(name_4, value_4);
  *json_object.add_object_properties() = MakeJsonProperty(name_5, value_5);
  *json_object.add_object_properties() = MakeJsonProperty(name_6, value_6);
  *json_object.add_object_properties() = MakeJsonProperty(name_7, value_7);
  *json_object.add_object_properties() = MakeJsonProperty(name_8, value_8);
  *json_object.add_object_properties() = MakeJsonProperty(name_9, value_9);
  *json_object.add_object_properties() = MakeJsonProperty(name_10, value_10);
  *json_object.add_object_properties() = MakeJsonProperty(name_11, value_11);
  *json_object.add_object_properties() = MakeJsonProperty(name_12, value_12);
  *json_object.add_object_properties() = MakeJsonProperty(name_13, value_13);
  return json_object;
}


template <typename Value1, typename Value2, typename Value3, typename Value4,
    typename Value5, typename Value6, typename Value7, typename Value8,
    typename Value9, typename Value10, typename Value11, typename Value12,
    typename Value13, typename Value14>
JsonValue MakeJsonObject(StringPiece name_1, Value1 value_1,
    StringPiece name_2, Value2 value_2, StringPiece name_3, Value3 value_3,
    StringPiece name_4, Value4 value_4, StringPiece name_5, Value5 value_5,
    StringPiece name_6, Value6 value_6, StringPiece name_7, Value7 value_7,
    StringPiece name_8, Value8 value_8, StringPiece name_9, Value9 value_9,
    StringPiece name_10, Value10 value_10, StringPiece name_11,
    Value11 value_11, StringPiece name_12, Value12 value_12,
    StringPiece name_13, Value13 value_13, StringPiece name_14,
    Value14 value_14) {
  JsonValue json_object = MakeJsonObject();
  *json_object.add_object_properties() = MakeJsonProperty(name_1, value_1);
  *json_object.add_object_properties() = MakeJsonProperty(name_2, value_2);
  *json_object.add_object_properties() = MakeJsonProperty(name_3, value_3);
  *json_object.add_object_properties() = MakeJsonProperty(name_4, value_4);
  *json_object.add_object_properties() = MakeJsonProperty(name_5, value_5);
  *json_object.add_object_properties() = MakeJsonProperty(name_6, value_6);
  *json_object.add_object_properties() = MakeJsonProperty(name_7, value_7);
  *json_object.add_object_properties() = MakeJsonProperty(name_8, value_8);
  *json_object.add_object_properties() = MakeJsonProperty(name_9, value_9);
  *json_object.add_object_properties() = MakeJsonProperty(name_10, value_10);
  *json_object.add_object_properties() = MakeJsonProperty(name_11, value_11);
  *json_object.add_object_properties() = MakeJsonProperty(name_12, value_12);
  *json_object.add_object_properties() = MakeJsonProperty(name_13, value_13);
  *json_object.add_object_properties() = MakeJsonProperty(name_14, value_14);
  return json_object;
}


template <typename Value1, typename Value2, typename Value3, typename Value4,
    typename Value5, typename Value6, typename Value7, typename Value8,
    typename Value9, typename Value10, typename Value11, typename Value12,
    typename Value13, typename Value14, typename Value15>
JsonValue MakeJsonObject(StringPiece name_1, Value1 value_1,
    StringPiece name_2, Value2 value_2, StringPiece name_3, Value3 value_3,
    StringPiece name_4, Value4 value_4, StringPiece name_5, Value5 value_5,
    StringPiece name_6, Value6 value_6, StringPiece name_7, Value7 value_7,
    StringPiece name_8, Value8 value_8, StringPiece name_9, Value9 value_9,
    StringPiece name_10, Value10 value_10, StringPiece name_11,
    Value11 value_11, StringPiece name_12, Value12 value_12,
    StringPiece name_13, Value13 value_13, StringPiece name_14,
    Value14 value_14, StringPiece name_15, Value15 value_15) {
  JsonValue json_object = MakeJsonObject();
  *json_object.add_object_properties() = MakeJsonProperty(name_1, value_1);
  *json_object.add_object_properties() = MakeJsonProperty(name_2, value_2);
  *json_object.add_object_properties() = MakeJsonProperty(name_3, value_3);
  *json_object.add_object_properties() = MakeJsonProperty(name_4, value_4);
  *json_object.add_object_properties() = MakeJsonProperty(name_5, value_5);
  *json_object.add_object_properties() = MakeJsonProperty(name_6, value_6);
  *json_object.add_object_properties() = MakeJsonProperty(name_7, value_7);
  *json_object.add_object_properties() = MakeJsonProperty(name_8, value_8);
  *json_object.add_object_properties() = MakeJsonProperty(name_9, value_9);
  *json_object.add_object_properties() = MakeJsonProperty(name_10, value_10);
  *json_object.add_object_properties() = MakeJsonProperty(name_11, value_11);
  *json_object.add_object_properties() = MakeJsonProperty(name_12, value_12);
  *json_object.add_object_properties() = MakeJsonProperty(name_13, value_13);
  *json_object.add_object_properties() = MakeJsonProperty(name_14, value_14);
  *json_object.add_object_properties() = MakeJsonProperty(name_15, value_15);
  return json_object;
}


template <typename Value1, typename Value2, typename Value3, typename Value4,
    typename Value5, typename Value6, typename Value7, typename Value8,
    typename Value9, typename Value10, typename Value11, typename Value12,
    typename Value13, typename Value14, typename Value15, typename Value16>
JsonValue MakeJsonObject(StringPiece name_1, Value1 value_1,
    StringPiece name_2, Value2 value_2, StringPiece name_3, Value3 value_3,
    StringPiece name_4, Value4 value_4, StringPiece name_5, Value5 value_5,
    StringPiece name_6, Value6 value_6, StringPiece name_7, Value7 value_7,
    StringPiece name_8, Value8 value_8, StringPiece name_9, Value9 value_9,
    StringPiece name_10, Value10 value_10, StringPiece name_11,
    Value11 value_11, StringPiece name_12, Value12 value_12,
    StringPiece name_13, Value13 value_13, StringPiece name_14,
    Value14 value_14, StringPiece name_15, Value15 value_15,
    StringPiece name_16, Value16 value_16) {
  JsonValue json_object = MakeJsonObject();
  *json_object.add_object_properties() = MakeJsonProperty(name_1, value_1);
  *json_object.add_object_properties() = MakeJsonProperty(name_2, value_2);
  *json_object.add_object_properties() = MakeJsonProperty(name_3, value_3);
  *json_object.add_object_properties() = MakeJsonProperty(name_4, value_4);
  *json_object.add_object_properties() = MakeJsonProperty(name_5, value_5);
  *json_object.add_object_properties() = MakeJsonProperty(name_6, value_6);
  *json_object.add_object_properties() = MakeJsonProperty(name_7, value_7);
  *json_object.add_object_properties() = MakeJsonProperty(name_8, value_8);
  *json_object.add_object_properties() = MakeJsonProperty(name_9, value_9);
  *json_object.add_object_properties() = MakeJsonProperty(name_10, value_10);
  *json_object.add_object_properties() = MakeJsonProperty(name_11, value_11);
  *json_object.add_object_properties() = MakeJsonProperty(name_12, value_12);
  *json_object.add_object_properties() = MakeJsonProperty(name_13, value_13);
  *json_object.add_object_properties() = MakeJsonProperty(name_14, value_14);
  *json_object.add_object_properties() = MakeJsonProperty(name_15, value_15);
  *json_object.add_object_properties() = MakeJsonProperty(name_16, value_16);
  return json_object;
}


template <typename Value1, typename Value2, typename Value3, typename Value4,
    typename Value5, typename Value6, typename Value7, typename Value8,
    typename Value9, typename Value10, typename Value11, typename Value12,
    typename Value13, typename Value14, typename Value15, typename Value16,
    typename Value17>
JsonValue MakeJsonObject(StringPiece name_1, Value1 value_1,
    StringPiece name_2, Value2 value_2, StringPiece name_3, Value3 value_3,
    StringPiece name_4, Value4 value_4, StringPiece name_5, Value5 value_5,
    StringPiece name_6, Value6 value_6, StringPiece name_7, Value7 value_7,
    StringPiece name_8, Value8 value_8, StringPiece name_9, Value9 value_9,
    StringPiece name_10, Value10 value_10, StringPiece name_11,
    Value11 value_11, StringPiece name_12, Value12 value_12,
    StringPiece name_13, Value13 value_13, StringPiece name_14,
    Value14 value_14, StringPiece name_15, Value15 value_15,
    StringPiece name_16, Value16 value_16, StringPiece name_17,
    Value17 value_17) {
  JsonValue json_object = MakeJsonObject();
  *json_object.add_object_properties() = MakeJsonProperty(name_1, value_1);
  *json_object.add_object_properties() = MakeJsonProperty(name_2, value_2);
  *json_object.add_object_properties() = MakeJsonProperty(name_3, value_3);
  *json_object.add_object_properties() = MakeJsonProperty(name_4, value_4);
  *json_object.add_object_properties() = MakeJsonProperty(name_5, value_5);
  *json_object.add_object_properties() = MakeJsonProperty(name_6, value_6);
  *json_object.add_object_properties() = MakeJsonProperty(name_7, value_7);
  *json_object.add_object_properties() = MakeJsonProperty(name_8, value_8);
  *json_object.add_object_properties() = MakeJsonProperty(name_9, value_9);
  *json_object.add_object_properties() = MakeJsonProperty(name_10, value_10);
  *json_object.add_object_properties() = MakeJsonProperty(name_11, value_11);
  *json_object.add_object_properties() = MakeJsonProperty(name_12, value_12);
  *json_object.add_object_properties() = MakeJsonProperty(name_13, value_13);
  *json_object.add_object_properties() = MakeJsonProperty(name_14, value_14);
  *json_object.add_object_properties() = MakeJsonProperty(name_15, value_15);
  *json_object.add_object_properties() = MakeJsonProperty(name_16, value_16);
  *json_object.add_object_properties() = MakeJsonProperty(name_17, value_17);
  return json_object;
}


template <typename Value1, typename Value2, typename Value3, typename Value4,
    typename Value5, typename Value6, typename Value7, typename Value8,
    typename Value9, typename Value10, typename Value11, typename Value12,
    typename Value13, typename Value14, typename Value15, typename Value16,
    typename Value17, typename Value18>
JsonValue MakeJsonObject(StringPiece name_1, Value1 value_1,
    StringPiece name_2, Value2 value_2, StringPiece name_3, Value3 value_3,
    StringPiece name_4, Value4 value_4, StringPiece name_5, Value5 value_5,
    StringPiece name_6, Value6 value_6, StringPiece name_7, Value7 value_7,
    StringPiece name_8, Value8 value_8, StringPiece name_9, Value9 value_9,
    StringPiece name_10, Value10 value_10, StringPiece name_11,
    Value11 value_11, StringPiece name_12, Value12 value_12,
    StringPiece name_13, Value13 value_13, StringPiece name_14,
    Value14 value_14, StringPiece name_15, Value15 value_15,
    StringPiece name_16, Value16 value_16, StringPiece name_17,
    Value17 value_17, StringPiece name_18, Value18 value_18) {
  JsonValue json_object = MakeJsonObject();
  *json_object.add_object_properties() = MakeJsonProperty(name_1, value_1);
  *json_object.add_object_properties() = MakeJsonProperty(name_2, value_2);
  *json_object.add_object_properties() = MakeJsonProperty(name_3, value_3);
  *json_object.add_object_properties() = MakeJsonProperty(name_4, value_4);
  *json_object.add_object_properties() = MakeJsonProperty(name_5, value_5);
  *json_object.add_object_properties() = MakeJsonProperty(name_6, value_6);
  *json_object.add_object_properties() = MakeJsonProperty(name_7, value_7);
  *json_object.add_object_properties() = MakeJsonProperty(name_8, value_8);
  *json_object.add_object_properties() = MakeJsonProperty(name_9, value_9);
  *json_object.add_object_properties() = MakeJsonProperty(name_10, value_10);
  *json_object.add_object_properties() = MakeJsonProperty(name_11, value_11);
  *json_object.add_object_properties() = MakeJsonProperty(name_12, value_12);
  *json_object.add_object_properties() = MakeJsonProperty(name_13, value_13);
  *json_object.add_object_properties() = MakeJsonProperty(name_14, value_14);
  *json_object.add_object_properties() = MakeJsonProperty(name_15, value_15);
  *json_object.add_object_properties() = MakeJsonProperty(name_16, value_16);
  *json_object.add_object_properties() = MakeJsonProperty(name_17, value_17);
  *json_object.add_object_properties() = MakeJsonProperty(name_18, value_18);
  return json_object;
}


template <typename Value1, typename Value2, typename Value3, typename Value4,
    typename Value5, typename Value6, typename Value7, typename Value8,
    typename Value9, typename Value10, typename Value11, typename Value12,
    typename Value13, typename Value14, typename Value15, typename Value16,
    typename Value17, typename Value18, typename Value19>
JsonValue MakeJsonObject(StringPiece name_1, Value1 value_1,
    StringPiece name_2, Value2 value_2, StringPiece name_3, Value3 value_3,
    StringPiece name_4, Value4 value_4, StringPiece name_5, Value5 value_5,
    StringPiece name_6, Value6 value_6, StringPiece name_7, Value7 value_7,
    StringPiece name_8, Value8 value_8, StringPiece name_9, Value9 value_9,
    StringPiece name_10, Value10 value_10, StringPiece name_11,
    Value11 value_11, StringPiece name_12, Value12 value_12,
    StringPiece name_13, Value13 value_13, StringPiece name_14,
    Value14 value_14, StringPiece name_15, Value15 value_15,
    StringPiece name_16, Value16 value_16, StringPiece name_17,
    Value17 value_17, StringPiece name_18, Value18 value_18,
    StringPiece name_19, Value19 value_19) {
  JsonValue json_object = MakeJsonObject();
  *json_object.add_object_properties() = MakeJsonProperty(name_1, value_1);
  *json_object.add_object_properties() = MakeJsonProperty(name_2, value_2);
  *json_object.add_object_properties() = MakeJsonProperty(name_3, value_3);
  *json_object.add_object_properties() = MakeJsonProperty(name_4, value_4);
  *json_object.add_object_properties() = MakeJsonProperty(name_5, value_5);
  *json_object.add_object_properties() = MakeJsonProperty(name_6, value_6);
  *json_object.add_object_properties() = MakeJsonProperty(name_7, value_7);
  *json_object.add_object_properties() = MakeJsonProperty(name_8, value_8);
  *json_object.add_object_properties() = MakeJsonProperty(name_9, value_9);
  *json_object.add_object_properties() = MakeJsonProperty(name_10, value_10);
  *json_object.add_object_properties() = MakeJsonProperty(name_11, value_11);
  *json_object.add_object_properties() = MakeJsonProperty(name_12, value_12);
  *json_object.add_object_properties() = MakeJsonProperty(name_13, value_13);
  *json_object.add_object_properties() = MakeJsonProperty(name_14, value_14);
  *json_object.add_object_properties() = MakeJsonProperty(name_15, value_15);
  *json_object.add_object_properties() = MakeJsonProperty(name_16, value_16);
  *json_object.add_object_properties() = MakeJsonProperty(name_17, value_17);
  *json_object.add_object_properties() = MakeJsonProperty(name_18, value_18);
  *json_object.add_object_properties() = MakeJsonProperty(name_19, value_19);
  return json_object;
}


template <typename Value1, typename Value2, typename Value3, typename Value4,
    typename Value5, typename Value6, typename Value7, typename Value8,
    typename Value9, typename Value10, typename Value11, typename Value12,
    typename Value13, typename Value14, typename Value15, typename Value16,
    typename Value17, typename Value18, typename Value19, typename Value20>
JsonValue MakeJsonObject(StringPiece name_1, Value1 value_1,
    StringPiece name_2, Value2 value_2, StringPiece name_3, Value3 value_3,
    StringPiece name_4, Value4 value_4, StringPiece name_5, Value5 value_5,
    StringPiece name_6, Value6 value_6, StringPiece name_7, Value7 value_7,
    StringPiece name_8, Value8 value_8, StringPiece name_9, Value9 value_9,
    StringPiece name_10, Value10 value_10, StringPiece name_11,
    Value11 value_11, StringPiece name_12, Value12 value_12,
    StringPiece name_13, Value13 value_13, StringPiece name_14,
    Value14 value_14, StringPiece name_15, Value15 value_15,
    StringPiece name_16, Value16 value_16, StringPiece name_17,
    Value17 value_17, StringPiece name_18, Value18 value_18,
    StringPiece name_19, Value19 value_19, StringPiece name_20,
    Value20 value_20) {
  JsonValue json_object = MakeJsonObject();
  *json_object.add_object_properties() = MakeJsonProperty(name_1, value_1);
  *json_object.add_object_properties() = MakeJsonProperty(name_2, value_2);
  *json_object.add_object_properties() = MakeJsonProperty(name_3, value_3);
  *json_object.add_object_properties() = MakeJsonProperty(name_4, value_4);
  *json_object.add_object_properties() = MakeJsonProperty(name_5, value_5);
  *json_object.add_object_properties() = MakeJsonProperty(name_6, value_6);
  *json_object.add_object_properties() = MakeJsonProperty(name_7, value_7);
  *json_object.add_object_properties() = MakeJsonProperty(name_8, value_8);
  *json_object.add_object_properties() = MakeJsonProperty(name_9, value_9);
  *json_object.add_object_properties() = MakeJsonProperty(name_10, value_10);
  *json_object.add_object_properties() = MakeJsonProperty(name_11, value_11);
  *json_object.add_object_properties() = MakeJsonProperty(name_12, value_12);
  *json_object.add_object_properties() = MakeJsonProperty(name_13, value_13);
  *json_object.add_object_properties() = MakeJsonProperty(name_14, value_14);
  *json_object.add_object_properties() = MakeJsonProperty(name_15, value_15);
  *json_object.add_object_properties() = MakeJsonProperty(name_16, value_16);
  *json_object.add_object_properties() = MakeJsonProperty(name_17, value_17);
  *json_object.add_object_properties() = MakeJsonProperty(name_18, value_18);
  *json_object.add_object_properties() = MakeJsonProperty(name_19, value_19);
  *json_object.add_object_properties() = MakeJsonProperty(name_20, value_20);
  return json_object;
}


template <typename Value1>
JsonValue MakeJsonArray(Value1 value_1) {
  JsonValue json_array = MakeJsonArray();
  *json_array.add_array_elements() = MakeJsonValue(value_1);
  return json_array;
}


template <typename Value1, typename Value2>
JsonValue MakeJsonArray(Value1 value_1, Value2 value_2) {
  JsonValue json_array = MakeJsonArray();
  *json_array.add_array_elements() = MakeJsonValue(value_1);
  *json_array.add_array_elements() = MakeJsonValue(value_2);
  return json_array;
}


template <typename Value1, typename Value2, typename Value3>
JsonValue MakeJsonArray(Value1 value_1, Value2 value_2, Value3 value_3) {
  JsonValue json_array = MakeJsonArray();
  *json_array.add_array_elements() = MakeJsonValue(value_1);
  *json_array.add_array_elements() = MakeJsonValue(value_2);
  *json_array.add_array_elements() = MakeJsonValue(value_3);
  return json_array;
}


template <typename Value1, typename Value2, typename Value3, typename Value4>
JsonValue MakeJsonArray(Value1 value_1, Value2 value_2, Value3 value_3,
    Value4 value_4) {
  JsonValue json_array = MakeJsonArray();
  *json_array.add_array_elements() = MakeJsonValue(value_1);
  *json_array.add_array_elements() = MakeJsonValue(value_2);
  *json_array.add_array_elements() = MakeJsonValue(value_3);
  *json_array.add_array_elements() = MakeJsonValue(value_4);
  return json_array;
}


template <typename Value1, typename Value2, typename Value3, typename Value4,
    typename Value5>
JsonValue MakeJsonArray(Value1 value_1, Value2 value_2, Value3 value_3,
    Value4 value_4, Value5 value_5) {
  JsonValue json_array = MakeJsonArray();
  *json_array.add_array_elements() = MakeJsonValue(value_1);
  *json_array.add_array_elements() = MakeJsonValue(value_2);
  *json_array.add_array_elements() = MakeJsonValue(value_3);
  *json_array.add_array_elements() = MakeJsonValue(value_4);
  *json_array.add_array_elements() = MakeJsonValue(value_5);
  return json_array;
}


template <typename Value1, typename Value2, typename Value3, typename Value4,
    typename Value5, typename Value6>
JsonValue MakeJsonArray(Value1 value_1, Value2 value_2, Value3 value_3,
    Value4 value_4, Value5 value_5, Value6 value_6) {
  JsonValue json_array = MakeJsonArray();
  *json_array.add_array_elements() = MakeJsonValue(value_1);
  *json_array.add_array_elements() = MakeJsonValue(value_2);
  *json_array.add_array_elements() = MakeJsonValue(value_3);
  *json_array.add_array_elements() = MakeJsonValue(value_4);
  *json_array.add_array_elements() = MakeJsonValue(value_5);
  *json_array.add_array_elements() = MakeJsonValue(value_6);
  return json_array;
}


template <typename Value1, typename Value2, typename Value3, typename Value4,
    typename Value5, typename Value6, typename Value7>
JsonValue MakeJsonArray(Value1 value_1, Value2 value_2, Value3 value_3,
    Value4 value_4, Value5 value_5, Value6 value_6, Value7 value_7) {
  JsonValue json_array = MakeJsonArray();
  *json_array.add_array_elements() = MakeJsonValue(value_1);
  *json_array.add_array_elements() = MakeJsonValue(value_2);
  *json_array.add_array_elements() = MakeJsonValue(value_3);
  *json_array.add_array_elements() = MakeJsonValue(value_4);
  *json_array.add_array_elements() = MakeJsonValue(value_5);
  *json_array.add_array_elements() = MakeJsonValue(value_6);
  *json_array.add_array_elements() = MakeJsonValue(value_7);
  return json_array;
}


template <typename Value1, typename Value2, typename Value3, typename Value4,
    typename Value5, typename Value6, typename Value7, typename Value8>
JsonValue MakeJsonArray(Value1 value_1, Value2 value_2, Value3 value_3,
    Value4 value_4, Value5 value_5, Value6 value_6, Value7 value_7,
    Value8 value_8) {
  JsonValue json_array = MakeJsonArray();
  *json_array.add_array_elements() = MakeJsonValue(value_1);
  *json_array.add_array_elements() = MakeJsonValue(value_2);
  *json_array.add_array_elements() = MakeJsonValue(value_3);
  *json_array.add_array_elements() = MakeJsonValue(value_4);
  *json_array.add_array_elements() = MakeJsonValue(value_5);
  *json_array.add_array_elements() = MakeJsonValue(value_6);
  *json_array.add_array_elements() = MakeJsonValue(value_7);
  *json_array.add_array_elements() = MakeJsonValue(value_8);
  return json_array;
}


template <typename Value1, typename Value2, typename Value3, typename Value4,
    typename Value5, typename Value6, typename Value7, typename Value8,
    typename Value9>
JsonValue MakeJsonArray(Value1 value_1, Value2 value_2, Value3 value_3,
    Value4 value_4, Value5 value_5, Value6 value_6, Value7 value_7,
    Value8 value_8, Value9 value_9) {
  JsonValue json_array = MakeJsonArray();
  *json_array.add_array_elements() = MakeJsonValue(value_1);
  *json_array.add_array_elements() = MakeJsonValue(value_2);
  *json_array.add_array_elements() = MakeJsonValue(value_3);
  *json_array.add_array_elements() = MakeJsonValue(value_4);
  *json_array.add_array_elements() = MakeJsonValue(value_5);
  *json_array.add_array_elements() = MakeJsonValue(value_6);
  *json_array.add_array_elements() = MakeJsonValue(value_7);
  *json_array.add_array_elements() = MakeJsonValue(value_8);
  *json_array.add_array_elements() = MakeJsonValue(value_9);
  return json_array;
}


template <typename Value1, typename Value2, typename Value3, typename Value4,
    typename Value5, typename Value6, typename Value7, typename Value8,
    typename Value9, typename Value10>
JsonValue MakeJsonArray(Value1 value_1, Value2 value_2, Value3 value_3,
    Value4 value_4, Value5 value_5, Value6 value_6, Value7 value_7,
    Value8 value_8, Value9 value_9, Value10 value_10) {
  JsonValue json_array = MakeJsonArray();
  *json_array.add_array_elements() = MakeJsonValue(value_1);
  *json_array.add_array_elements() = MakeJsonValue(value_2);
  *json_array.add_array_elements() = MakeJsonValue(value_3);
  *json_array.add_array_elements() = MakeJsonValue(value_4);
  *json_array.add_array_elements() = MakeJsonValue(value_5);
  *json_array.add_array_elements() = MakeJsonValue(value_6);
  *json_array.add_array_elements() = MakeJsonValue(value_7);
  *json_array.add_array_elements() = MakeJsonValue(value_8);
  *json_array.add_array_elements() = MakeJsonValue(value_9);
  *json_array.add_array_elements() = MakeJsonValue(value_10);
  return json_array;
}


template <typename Value1, typename Value2, typename Value3, typename Value4,
    typename Value5, typename Value6, typename Value7, typename Value8,
    typename Value9, typename Value10, typename Value11>
JsonValue MakeJsonArray(Value1 value_1, Value2 value_2, Value3 value_3,
    Value4 value_4, Value5 value_5, Value6 value_6, Value7 value_7,
    Value8 value_8, Value9 value_9, Value10 value_10, Value11 value_11) {
  JsonValue json_array = MakeJsonArray();
  *json_array.add_array_elements() = MakeJsonValue(value_1);
  *json_array.add_array_elements() = MakeJsonValue(value_2);
  *json_array.add_array_elements() = MakeJsonValue(value_3);
  *json_array.add_array_elements() = MakeJsonValue(value_4);
  *json_array.add_array_elements() = MakeJsonValue(value_5);
  *json_array.add_array_elements() = MakeJsonValue(value_6);
  *json_array.add_array_elements() = MakeJsonValue(value_7);
  *json_array.add_array_elements() = MakeJsonValue(value_8);
  *json_array.add_array_elements() = MakeJsonValue(value_9);
  *json_array.add_array_elements() = MakeJsonValue(value_10);
  *json_array.add_array_elements() = MakeJsonValue(value_11);
  return json_array;
}


template <typename Value1, typename Value2, typename Value3, typename Value4,
    typename Value5, typename Value6, typename Value7, typename Value8,
    typename Value9, typename Value10, typename Value11, typename Value12>
JsonValue MakeJsonArray(Value1 value_1, Value2 value_2, Value3 value_3,
    Value4 value_4, Value5 value_5, Value6 value_6, Value7 value_7,
    Value8 value_8, Value9 value_9, Value10 value_10, Value11 value_11,
    Value12 value_12) {
  JsonValue json_array = MakeJsonArray();
  *json_array.add_array_elements() = MakeJsonValue(value_1);
  *json_array.add_array_elements() = MakeJsonValue(value_2);
  *json_array.add_array_elements() = MakeJsonValue(value_3);
  *json_array.add_array_elements() = MakeJsonValue(value_4);
  *json_array.add_array_elements() = MakeJsonValue(value_5);
  *json_array.add_array_elements() = MakeJsonValue(value_6);
  *json_array.add_array_elements() = MakeJsonValue(value_7);
  *json_array.add_array_elements() = MakeJsonValue(value_8);
  *json_array.add_array_elements() = MakeJsonValue(value_9);
  *json_array.add_array_elements() = MakeJsonValue(value_10);
  *json_array.add_array_elements() = MakeJsonValue(value_11);
  *json_array.add_array_elements() = MakeJsonValue(value_12);
  return json_array;
}


template <typename Value1, typename Value2, typename Value3, typename Value4,
    typename Value5, typename Value6, typename Value7, typename Value8,
    typename Value9, typename Value10, typename Value11, typename Value12,
    typename Value13>
JsonValue MakeJsonArray(Value1 value_1, Value2 value_2, Value3 value_3,
    Value4 value_4, Value5 value_5, Value6 value_6, Value7 value_7,
    Value8 value_8, Value9 value_9, Value10 value_10, Value11 value_11,
    Value12 value_12, Value13 value_13) {
  JsonValue json_array = MakeJsonArray();
  *json_array.add_array_elements() = MakeJsonValue(value_1);
  *json_array.add_array_elements() = MakeJsonValue(value_2);
  *json_array.add_array_elements() = MakeJsonValue(value_3);
  *json_array.add_array_elements() = MakeJsonValue(value_4);
  *json_array.add_array_elements() = MakeJsonValue(value_5);
  *json_array.add_array_elements() = MakeJsonValue(value_6);
  *json_array.add_array_elements() = MakeJsonValue(value_7);
  *json_array.add_array_elements() = MakeJsonValue(value_8);
  *json_array.add_array_elements() = MakeJsonValue(value_9);
  *json_array.add_array_elements() = MakeJsonValue(value_10);
  *json_array.add_array_elements() = MakeJsonValue(value_11);
  *json_array.add_array_elements() = MakeJsonValue(value_12);
  *json_array.add_array_elements() = MakeJsonValue(value_13);
  return json_array;
}


template <typename Value1, typename Value2, typename Value3, typename Value4,
    typename Value5, typename Value6, typename Value7, typename Value8,
    typename Value9, typename Value10, typename Value11, typename Value12,
    typename Value13, typename Value14>
JsonValue MakeJsonArray(Value1 value_1, Value2 value_2, Value3 value_3,
    Value4 value_4, Value5 value_5, Value6 value_6, Value7 value_7,
    Value8 value_8, Value9 value_9, Value10 value_10, Value11 value_11,
    Value12 value_12, Value13 value_13, Value14 value_14) {
  JsonValue json_array = MakeJsonArray();
  *json_array.add_array_elements() = MakeJsonValue(value_1);
  *json_array.add_array_elements() = MakeJsonValue(value_2);
  *json_array.add_array_elements() = MakeJsonValue(value_3);
  *json_array.add_array_elements() = MakeJsonValue(value_4);
  *json_array.add_array_elements() = MakeJsonValue(value_5);
  *json_array.add_array_elements() = MakeJsonValue(value_6);
  *json_array.add_array_elements() = MakeJsonValue(value_7);
  *json_array.add_array_elements() = MakeJsonValue(value_8);
  *json_array.add_array_elements() = MakeJsonValue(value_9);
  *json_array.add_array_elements() = MakeJsonValue(value_10);
  *json_array.add_array_elements() = MakeJsonValue(value_11);
  *json_array.add_array_elements() = MakeJsonValue(value_12);
  *json_array.add_array_elements() = MakeJsonValue(value_13);
  *json_array.add_array_elements() = MakeJsonValue(value_14);
  return json_array;
}


template <typename Value1, typename Value2, typename Value3, typename Value4,
    typename Value5, typename Value6, typename Value7, typename Value8,
    typename Value9, typename Value10, typename Value11, typename Value12,
    typename Value13, typename Value14, typename Value15>
JsonValue MakeJsonArray(Value1 value_1, Value2 value_2, Value3 value_3,
    Value4 value_4, Value5 value_5, Value6 value_6, Value7 value_7,
    Value8 value_8, Value9 value_9, Value10 value_10, Value11 value_11,
    Value12 value_12, Value13 value_13, Value14 value_14, Value15 value_15) {
  JsonValue json_array = MakeJsonArray();
  *json_array.add_array_elements() = MakeJsonValue(value_1);
  *json_array.add_array_elements() = MakeJsonValue(value_2);
  *json_array.add_array_elements() = MakeJsonValue(value_3);
  *json_array.add_array_elements() = MakeJsonValue(value_4);
  *json_array.add_array_elements() = MakeJsonValue(value_5);
  *json_array.add_array_elements() = MakeJsonValue(value_6);
  *json_array.add_array_elements() = MakeJsonValue(value_7);
  *json_array.add_array_elements() = MakeJsonValue(value_8);
  *json_array.add_array_elements() = MakeJsonValue(value_9);
  *json_array.add_array_elements() = MakeJsonValue(value_10);
  *json_array.add_array_elements() = MakeJsonValue(value_11);
  *json_array.add_array_elements() = MakeJsonValue(value_12);
  *json_array.add_array_elements() = MakeJsonValue(value_13);
  *json_array.add_array_elements() = MakeJsonValue(value_14);
  *json_array.add_array_elements() = MakeJsonValue(value_15);
  return json_array;
}


template <typename Value1, typename Value2, typename Value3, typename Value4,
    typename Value5, typename Value6, typename Value7, typename Value8,
    typename Value9, typename Value10, typename Value11, typename Value12,
    typename Value13, typename Value14, typename Value15, typename Value16>
JsonValue MakeJsonArray(Value1 value_1, Value2 value_2, Value3 value_3,
    Value4 value_4, Value5 value_5, Value6 value_6, Value7 value_7,
    Value8 value_8, Value9 value_9, Value10 value_10, Value11 value_11,
    Value12 value_12, Value13 value_13, Value14 value_14, Value15 value_15,
    Value16 value_16) {
  JsonValue json_array = MakeJsonArray();
  *json_array.add_array_elements() = MakeJsonValue(value_1);
  *json_array.add_array_elements() = MakeJsonValue(value_2);
  *json_array.add_array_elements() = MakeJsonValue(value_3);
  *json_array.add_array_elements() = MakeJsonValue(value_4);
  *json_array.add_array_elements() = MakeJsonValue(value_5);
  *json_array.add_array_elements() = MakeJsonValue(value_6);
  *json_array.add_array_elements() = MakeJsonValue(value_7);
  *json_array.add_array_elements() = MakeJsonValue(value_8);
  *json_array.add_array_elements() = MakeJsonValue(value_9);
  *json_array.add_array_elements() = MakeJsonValue(value_10);
  *json_array.add_array_elements() = MakeJsonValue(value_11);
  *json_array.add_array_elements() = MakeJsonValue(value_12);
  *json_array.add_array_elements() = MakeJsonValue(value_13);
  *json_array.add_array_elements() = MakeJsonValue(value_14);
  *json_array.add_array_elements() = MakeJsonValue(value_15);
  *json_array.add_array_elements() = MakeJsonValue(value_16);
  return json_array;
}


template <typename Value1, typename Value2, typename Value3, typename Value4,
    typename Value5, typename Value6, typename Value7, typename Value8,
    typename Value9, typename Value10, typename Value11, typename Value12,
    typename Value13, typename Value14, typename Value15, typename Value16,
    typename Value17>
JsonValue MakeJsonArray(Value1 value_1, Value2 value_2, Value3 value_3,
    Value4 value_4, Value5 value_5, Value6 value_6, Value7 value_7,
    Value8 value_8, Value9 value_9, Value10 value_10, Value11 value_11,
    Value12 value_12, Value13 value_13, Value14 value_14, Value15 value_15,
    Value16 value_16, Value17 value_17) {
  JsonValue json_array = MakeJsonArray();
  *json_array.add_array_elements() = MakeJsonValue(value_1);
  *json_array.add_array_elements() = MakeJsonValue(value_2);
  *json_array.add_array_elements() = MakeJsonValue(value_3);
  *json_array.add_array_elements() = MakeJsonValue(value_4);
  *json_array.add_array_elements() = MakeJsonValue(value_5);
  *json_array.add_array_elements() = MakeJsonValue(value_6);
  *json_array.add_array_elements() = MakeJsonValue(value_7);
  *json_array.add_array_elements() = MakeJsonValue(value_8);
  *json_array.add_array_elements() = MakeJsonValue(value_9);
  *json_array.add_array_elements() = MakeJsonValue(value_10);
  *json_array.add_array_elements() = MakeJsonValue(value_11);
  *json_array.add_array_elements() = MakeJsonValue(value_12);
  *json_array.add_array_elements() = MakeJsonValue(value_13);
  *json_array.add_array_elements() = MakeJsonValue(value_14);
  *json_array.add_array_elements() = MakeJsonValue(value_15);
  *json_array.add_array_elements() = MakeJsonValue(value_16);
  *json_array.add_array_elements() = MakeJsonValue(value_17);
  return json_array;
}


template <typename Value1, typename Value2, typename Value3, typename Value4,
    typename Value5, typename Value6, typename Value7, typename Value8,
    typename Value9, typename Value10, typename Value11, typename Value12,
    typename Value13, typename Value14, typename Value15, typename Value16,
    typename Value17, typename Value18>
JsonValue MakeJsonArray(Value1 value_1, Value2 value_2, Value3 value_3,
    Value4 value_4, Value5 value_5, Value6 value_6, Value7 value_7,
    Value8 value_8, Value9 value_9, Value10 value_10, Value11 value_11,
    Value12 value_12, Value13 value_13, Value14 value_14, Value15 value_15,
    Value16 value_16, Value17 value_17, Value18 value_18) {
  JsonValue json_array = MakeJsonArray();
  *json_array.add_array_elements() = MakeJsonValue(value_1);
  *json_array.add_array_elements() = MakeJsonValue(value_2);
  *json_array.add_array_elements() = MakeJsonValue(value_3);
  *json_array.add_array_elements() = MakeJsonValue(value_4);
  *json_array.add_array_elements() = MakeJsonValue(value_5);
  *json_array.add_array_elements() = MakeJsonValue(value_6);
  *json_array.add_array_elements() = MakeJsonValue(value_7);
  *json_array.add_array_elements() = MakeJsonValue(value_8);
  *json_array.add_array_elements() = MakeJsonValue(value_9);
  *json_array.add_array_elements() = MakeJsonValue(value_10);
  *json_array.add_array_elements() = MakeJsonValue(value_11);
  *json_array.add_array_elements() = MakeJsonValue(value_12);
  *json_array.add_array_elements() = MakeJsonValue(value_13);
  *json_array.add_array_elements() = MakeJsonValue(value_14);
  *json_array.add_array_elements() = MakeJsonValue(value_15);
  *json_array.add_array_elements() = MakeJsonValue(value_16);
  *json_array.add_array_elements() = MakeJsonValue(value_17);
  *json_array.add_array_elements() = MakeJsonValue(value_18);
  return json_array;
}


template <typename Value1, typename Value2, typename Value3, typename Value4,
    typename Value5, typename Value6, typename Value7, typename Value8,
    typename Value9, typename Value10, typename Value11, typename Value12,
    typename Value13, typename Value14, typename Value15, typename Value16,
    typename Value17, typename Value18, typename Value19>
JsonValue MakeJsonArray(Value1 value_1, Value2 value_2, Value3 value_3,
    Value4 value_4, Value5 value_5, Value6 value_6, Value7 value_7,
    Value8 value_8, Value9 value_9, Value10 value_10, Value11 value_11,
    Value12 value_12, Value13 value_13, Value14 value_14, Value15 value_15,
    Value16 value_16, Value17 value_17, Value18 value_18, Value19 value_19) {
  JsonValue json_array = MakeJsonArray();
  *json_array.add_array_elements() = MakeJsonValue(value_1);
  *json_array.add_array_elements() = MakeJsonValue(value_2);
  *json_array.add_array_elements() = MakeJsonValue(value_3);
  *json_array.add_array_elements() = MakeJsonValue(value_4);
  *json_array.add_array_elements() = MakeJsonValue(value_5);
  *json_array.add_array_elements() = MakeJsonValue(value_6);
  *json_array.add_array_elements() = MakeJsonValue(value_7);
  *json_array.add_array_elements() = MakeJsonValue(value_8);
  *json_array.add_array_elements() = MakeJsonValue(value_9);
  *json_array.add_array_elements() = MakeJsonValue(value_10);
  *json_array.add_array_elements() = MakeJsonValue(value_11);
  *json_array.add_array_elements() = MakeJsonValue(value_12);
  *json_array.add_array_elements() = MakeJsonValue(value_13);
  *json_array.add_array_elements() = MakeJsonValue(value_14);
  *json_array.add_array_elements() = MakeJsonValue(value_15);
  *json_array.add_array_elements() = MakeJsonValue(value_16);
  *json_array.add_array_elements() = MakeJsonValue(value_17);
  *json_array.add_array_elements() = MakeJsonValue(value_18);
  *json_array.add_array_elements() = MakeJsonValue(value_19);
  return json_array;
}


template <typename Value1, typename Value2, typename Value3, typename Value4,
    typename Value5, typename Value6, typename Value7, typename Value8,
    typename Value9, typename Value10, typename Value11, typename Value12,
    typename Value13, typename Value14, typename Value15, typename Value16,
    typename Value17, typename Value18, typename Value19, typename Value20>
JsonValue MakeJsonArray(Value1 value_1, Value2 value_2, Value3 value_3,
    Value4 value_4, Value5 value_5, Value6 value_6, Value7 value_7,
    Value8 value_8, Value9 value_9, Value10 value_10, Value11 value_11,
    Value12 value_12, Value13 value_13, Value14 value_14, Value15 value_15,
    Value16 value_16, Value17 value_17, Value18 value_18, Value19 value_19,
    Value20 value_20) {
  JsonValue json_array = MakeJsonArray();
  *json_array.add_array_elements() = MakeJsonValue(value_1);
  *json_array.add_array_elements() = MakeJsonValue(value_2);
  *json_array.add_array_elements() = MakeJsonValue(value_3);
  *json_array.add_array_elements() = MakeJsonValue(value_4);
  *json_array.add_array_elements() = MakeJsonValue(value_5);
  *json_array.add_array_elements() = MakeJsonValue(value_6);
  *json_array.add_array_elements() = MakeJsonValue(value_7);
  *json_array.add_array_elements() = MakeJsonValue(value_8);
  *json_array.add_array_elements() = MakeJsonValue(value_9);
  *json_array.add_array_elements() = MakeJsonValue(value_10);
  *json_array.add_array_elements() = MakeJsonValue(value_11);
  *json_array.add_array_elements() = MakeJsonValue(value_12);
  *json_array.add_array_elements() = MakeJsonValue(value_13);
  *json_array.add_array_elements() = MakeJsonValue(value_14);
  *json_array.add_array_elements() = MakeJsonValue(value_15);
  *json_array.add_array_elements() = MakeJsonValue(value_16);
  *json_array.add_array_elements() = MakeJsonValue(value_17);
  *json_array.add_array_elements() = MakeJsonValue(value_18);
  *json_array.add_array_elements() = MakeJsonValue(value_19);
  *json_array.add_array_elements() = MakeJsonValue(value_20);
  return json_array;
}



}  // namespace pjcore

#endif  // PJCORE_MAKE_JSON_VALUE_PUMP_H_
