// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pjcore/error.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "pjcore/error.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace pjcore {

namespace {

const ::google::protobuf::Descriptor* TextLocation_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TextLocation_reflection_ = NULL;
const ::google::protobuf::Descriptor* Error_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Error_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* HttpStatusCode_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_pjcore_2ferror_2eproto() {
  protobuf_AddDesc_pjcore_2ferror_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "pjcore/error.proto");
  GOOGLE_CHECK(file != NULL);
  TextLocation_descriptor_ = file->message_type(0);
  static const int TextLocation_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TextLocation, offset_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TextLocation, line_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TextLocation, column_),
  };
  TextLocation_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      TextLocation_descriptor_,
      TextLocation::default_instance_,
      TextLocation_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TextLocation, _has_bits_[0]),
      -1,
      -1,
      sizeof(TextLocation),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TextLocation, _internal_metadata_));
  Error_descriptor_ = file->message_type(1);
  static const int Error_offsets_[15] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Error, description_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Error, source_file_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Error, source_line_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Error, system_errno_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Error, system_errno_description_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Error, uv_errno_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Error, uv_errno_description_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Error, http_errno_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Error, http_errno_description_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Error, http_status_code_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Error, http_reason_phrase_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Error, json_path_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Error, text_location_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Error, object_properties_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Error, cause_),
  };
  Error_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Error_descriptor_,
      Error::default_instance_,
      Error_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Error, _has_bits_[0]),
      -1,
      -1,
      sizeof(Error),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Error, _internal_metadata_));
  HttpStatusCode_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_pjcore_2ferror_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      TextLocation_descriptor_, &TextLocation::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Error_descriptor_, &Error::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_pjcore_2ferror_2eproto() {
  delete TextLocation::default_instance_;
  delete TextLocation_reflection_;
  delete Error::default_instance_;
  delete Error_reflection_;
}

void protobuf_AddDesc_pjcore_2ferror_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::pjcore::protobuf_AddDesc_pjcore_2fjson_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\022pjcore/error.proto\022\006pjcore\032\021pjcore/jso"
    "n.proto\"B\n\014TextLocation\022\016\n\006offset\030\001 \001(\004\022"
    "\017\n\004line\030\002 \001(\004:\0011\022\021\n\006column\030\003 \001(\004:\0011\"\305\003\n\005"
    "Error\022\023\n\013description\030\001 \001(\t\022\023\n\013source_fil"
    "e\030\002 \001(\t\022\023\n\013source_line\030\003 \001(\005\022\024\n\014system_e"
    "rrno\030\004 \001(\005\022 \n\030system_errno_description\030\005"
    " \001(\t\022\020\n\010uv_errno\030\006 \001(\005\022\034\n\024uv_errno_descr"
    "iption\030\007 \001(\t\022\022\n\nhttp_errno\030\010 \001(\005\022\036\n\026http"
    "_errno_description\030\t \001(\t\0220\n\020http_status_"
    "code\030\n \001(\0162\026.pjcore.HttpStatusCode\022\032\n\022ht"
    "tp_reason_phrase\030\013 \001(\t\022\021\n\tjson_path\030\014 \001("
    "\t\022+\n\rtext_location\030\r \001(\0132\024.pjcore.TextLo"
    "cation\0225\n\021object_properties\030\016 \003(\0132\032.pjco"
    "re.JsonValue.Property\022\034\n\005cause\030\017 \001(\0132\r.p"
    "jcore.Error*\304\014\n\016HttpStatusCode\022\035\n\031HTTP_S"
    "TATUS_CODE_CONTINUE\020d\022(\n$HTTP_STATUS_COD"
    "E_SWITCHING_PROTOCOLS\020e\022\030\n\023HTTP_STATUS_C"
    "ODE_OK\020\310\001\022\035\n\030HTTP_STATUS_CODE_CREATED\020\311\001"
    "\022\036\n\031HTTP_STATUS_CODE_ACCEPTED\020\312\001\0223\n.HTTP"
    "_STATUS_CODE_NON_AUTHORITATIVE_INFORMATI"
    "ON\020\313\001\022 \n\033HTTP_STATUS_CODE_NO_CONTENT\020\314\001\022"
    "#\n\036HTTP_STATUS_CODE_RESET_CONTENT\020\315\001\022%\n "
    "HTTP_STATUS_CODE_PARTIAL_CONTENT\020\316\001\022&\n!H"
    "TTP_STATUS_CODE_MULTIPLE_CHOICES\020\254\002\022\'\n\"H"
    "TTP_STATUS_CODE_MOVED_PERMANENTLY\020\255\002\022\033\n\026"
    "HTTP_STATUS_CODE_FOUND\020\256\002\022\037\n\032HTTP_STATUS"
    "_CODE_SEE_OTHER\020\257\002\022\"\n\035HTTP_STATUS_CODE_N"
    "OT_MODIFIED\020\260\002\022\037\n\032HTTP_STATUS_CODE_USE_P"
    "ROXY\020\261\002\022\036\n\031HTTP_STATUS_CODE__UNUSED_\020\262\002\022"
    "(\n#HTTP_STATUS_CODE_TEMPORARY_REDIRECT\020\263"
    "\002\022!\n\034HTTP_STATUS_CODE_BAD_REQUEST\020\220\003\022\"\n\035"
    "HTTP_STATUS_CODE_UNAUTHORIZED\020\221\003\022&\n!HTTP"
    "_STATUS_CODE_PAYMENT_REQUIRED\020\222\003\022\037\n\032HTTP"
    "_STATUS_CODE_FORBIDDEN\020\223\003\022\037\n\032HTTP_STATUS"
    "_CODE_NOT_FOUND\020\224\003\022(\n#HTTP_STATUS_CODE_M"
    "ETHOD_NOT_ALLOWED\020\225\003\022$\n\037HTTP_STATUS_CODE"
    "_NOT_ACCEPTABLE\020\226\003\0223\n.HTTP_STATUS_CODE_P"
    "ROXY_AUTHENTICATION_REQUIRED\020\227\003\022%\n HTTP_"
    "STATUS_CODE_REQUEST_TIMEOUT\020\230\003\022\036\n\031HTTP_S"
    "TATUS_CODE_CONFLICT\020\231\003\022\032\n\025HTTP_STATUS_CO"
    "DE_GONE\020\232\003\022%\n HTTP_STATUS_CODE_LENGTH_RE"
    "QUIRED\020\233\003\022)\n$HTTP_STATUS_CODE_PRECONDITI"
    "ON_FAILED\020\234\003\022.\n)HTTP_STATUS_CODE_REQUEST"
    "_ENTITY_TOO_LARGE\020\235\003\022*\n%HTTP_STATUS_CODE"
    "_REQUEST_URI_TOO_LONG\020\236\003\022,\n\'HTTP_STATUS_"
    "CODE_UNSUPPORTED_MEDIA_TYPE\020\237\003\0225\n0HTTP_S"
    "TATUS_CODE_REQUESTED_RANGE_NOT_SATISFIAB"
    "LE\020\240\003\022(\n#HTTP_STATUS_CODE_EXPECTATION_FA"
    "ILED\020\241\003\022+\n&HTTP_STATUS_CODE_INTERNAL_SER"
    "VER_ERROR\020\364\003\022%\n HTTP_STATUS_CODE_NOT_IMP"
    "LEMENTED\020\365\003\022!\n\034HTTP_STATUS_CODE_BAD_GATE"
    "WAY\020\366\003\022)\n$HTTP_STATUS_CODE_SERVICE_UNAVA"
    "ILABLE\020\367\003\022%\n HTTP_STATUS_CODE_GATEWAY_TI"
    "MEOUT\020\370\003\0220\n+HTTP_STATUS_CODE_HTTP_VERSIO"
    "N_NOT_SUPPORTED\020\371\003", 2178);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "pjcore/error.proto", &protobuf_RegisterTypes);
  TextLocation::default_instance_ = new TextLocation();
  Error::default_instance_ = new Error();
  TextLocation::default_instance_->InitAsDefaultInstance();
  Error::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_pjcore_2ferror_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_pjcore_2ferror_2eproto {
  StaticDescriptorInitializer_pjcore_2ferror_2eproto() {
    protobuf_AddDesc_pjcore_2ferror_2eproto();
  }
} static_descriptor_initializer_pjcore_2ferror_2eproto_;
const ::google::protobuf::EnumDescriptor* HttpStatusCode_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return HttpStatusCode_descriptor_;
}
bool HttpStatusCode_IsValid(int value) {
  switch(value) {
    case 100:
    case 101:
    case 200:
    case 201:
    case 202:
    case 203:
    case 204:
    case 205:
    case 206:
    case 300:
    case 301:
    case 302:
    case 303:
    case 304:
    case 305:
    case 306:
    case 307:
    case 400:
    case 401:
    case 402:
    case 403:
    case 404:
    case 405:
    case 406:
    case 407:
    case 408:
    case 409:
    case 410:
    case 411:
    case 412:
    case 413:
    case 414:
    case 415:
    case 416:
    case 417:
    case 500:
    case 501:
    case 502:
    case 503:
    case 504:
    case 505:
      return true;
    default:
      return false;
  }
}


namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#ifndef _MSC_VER
const int TextLocation::kOffsetFieldNumber;
const int TextLocation::kLineFieldNumber;
const int TextLocation::kColumnFieldNumber;
#endif  // !_MSC_VER

TextLocation::TextLocation()
  : ::google::protobuf::Message() , _internal_metadata_(NULL)  {
  SharedCtor();
  // @@protoc_insertion_point(constructor:pjcore.TextLocation)
}

void TextLocation::InitAsDefaultInstance() {
}

TextLocation::TextLocation(const TextLocation& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:pjcore.TextLocation)
}

void TextLocation::SharedCtor() {
  _cached_size_ = 0;
  offset_ = GOOGLE_ULONGLONG(0);
  line_ = GOOGLE_ULONGLONG(1);
  column_ = GOOGLE_ULONGLONG(1);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

TextLocation::~TextLocation() {
  // @@protoc_insertion_point(destructor:pjcore.TextLocation)
  SharedDtor();
}

void TextLocation::SharedDtor() {
  if (this != default_instance_) {
  }
}

void TextLocation::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TextLocation::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TextLocation_descriptor_;
}

const TextLocation& TextLocation::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_pjcore_2ferror_2eproto();
  return *default_instance_;
}

TextLocation* TextLocation::default_instance_ = NULL;

TextLocation* TextLocation::New(::google::protobuf::Arena* arena) const {
  TextLocation* n = new TextLocation;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void TextLocation::Clear() {
  if (_has_bits_[0 / 32] & 7) {
    offset_ = GOOGLE_ULONGLONG(0);
    line_ = GOOGLE_ULONGLONG(1);
    column_ = GOOGLE_ULONGLONG(1);
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool TextLocation::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pjcore.TextLocation)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint64 offset = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &offset_)));
          set_has_offset();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_line;
        break;
      }

      // optional uint64 line = 2 [default = 1];
      case 2: {
        if (tag == 16) {
         parse_line:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &line_)));
          set_has_line();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_column;
        break;
      }

      // optional uint64 column = 3 [default = 1];
      case 3: {
        if (tag == 24) {
         parse_column:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &column_)));
          set_has_column();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pjcore.TextLocation)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pjcore.TextLocation)
  return false;
#undef DO_
}

void TextLocation::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pjcore.TextLocation)
  // optional uint64 offset = 1;
  if (has_offset()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->offset(), output);
  }

  // optional uint64 line = 2 [default = 1];
  if (has_line()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(2, this->line(), output);
  }

  // optional uint64 column = 3 [default = 1];
  if (has_column()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(3, this->column(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:pjcore.TextLocation)
}

::google::protobuf::uint8* TextLocation::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:pjcore.TextLocation)
  // optional uint64 offset = 1;
  if (has_offset()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->offset(), target);
  }

  // optional uint64 line = 2 [default = 1];
  if (has_line()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(2, this->line(), target);
  }

  // optional uint64 column = 3 [default = 1];
  if (has_column()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(3, this->column(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pjcore.TextLocation)
  return target;
}

int TextLocation::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & 7) {
    // optional uint64 offset = 1;
    if (has_offset()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->offset());
    }

    // optional uint64 line = 2 [default = 1];
    if (has_line()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->line());
    }

    // optional uint64 column = 3 [default = 1];
    if (has_column()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->column());
    }

  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TextLocation::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const TextLocation* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const TextLocation*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void TextLocation::MergeFrom(const TextLocation& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_offset()) {
      set_offset(from.offset());
    }
    if (from.has_line()) {
      set_line(from.line());
    }
    if (from.has_column()) {
      set_column(from.column());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void TextLocation::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TextLocation::CopyFrom(const TextLocation& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TextLocation::IsInitialized() const {

  return true;
}

void TextLocation::Swap(TextLocation* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TextLocation::InternalSwap(TextLocation* other) {
  std::swap(offset_, other->offset_);
  std::swap(line_, other->line_);
  std::swap(column_, other->column_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata TextLocation::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TextLocation_descriptor_;
  metadata.reflection = TextLocation_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int Error::kDescriptionFieldNumber;
const int Error::kSourceFileFieldNumber;
const int Error::kSourceLineFieldNumber;
const int Error::kSystemErrnoFieldNumber;
const int Error::kSystemErrnoDescriptionFieldNumber;
const int Error::kUvErrnoFieldNumber;
const int Error::kUvErrnoDescriptionFieldNumber;
const int Error::kHttpErrnoFieldNumber;
const int Error::kHttpErrnoDescriptionFieldNumber;
const int Error::kHttpStatusCodeFieldNumber;
const int Error::kHttpReasonPhraseFieldNumber;
const int Error::kJsonPathFieldNumber;
const int Error::kTextLocationFieldNumber;
const int Error::kObjectPropertiesFieldNumber;
const int Error::kCauseFieldNumber;
#endif  // !_MSC_VER

Error::Error()
  : ::google::protobuf::Message() , _internal_metadata_(NULL)  {
  SharedCtor();
  // @@protoc_insertion_point(constructor:pjcore.Error)
}

void Error::InitAsDefaultInstance() {
  text_location_ = const_cast< ::pjcore::TextLocation*>(&::pjcore::TextLocation::default_instance());
  cause_ = const_cast< ::pjcore::Error*>(&::pjcore::Error::default_instance());
}

Error::Error(const Error& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:pjcore.Error)
}

void Error::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  description_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  source_file_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  source_line_ = 0;
  system_errno_ = 0;
  system_errno_description_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  uv_errno_ = 0;
  uv_errno_description_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  http_errno_ = 0;
  http_errno_description_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  http_status_code_ = 100;
  http_reason_phrase_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  json_path_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  text_location_ = NULL;
  cause_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Error::~Error() {
  // @@protoc_insertion_point(destructor:pjcore.Error)
  SharedDtor();
}

void Error::SharedDtor() {
  description_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  source_file_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  system_errno_description_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  uv_errno_description_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  http_errno_description_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  http_reason_phrase_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  json_path_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
    delete text_location_;
    delete cause_;
  }
}

void Error::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Error::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Error_descriptor_;
}

const Error& Error::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_pjcore_2ferror_2eproto();
  return *default_instance_;
}

Error* Error::default_instance_ = NULL;

Error* Error::New(::google::protobuf::Arena* arena) const {
  Error* n = new Error;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Error::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<Error*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 255) {
    ZR_(source_line_, system_errno_);
    ZR_(uv_errno_, http_errno_);
    if (has_description()) {
      description_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_source_file()) {
      source_file_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_system_errno_description()) {
      system_errno_description_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_uv_errno_description()) {
      uv_errno_description_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
  }
  if (_has_bits_[8 / 32] & 24320) {
    if (has_http_errno_description()) {
      http_errno_description_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    http_status_code_ = 100;
    if (has_http_reason_phrase()) {
      http_reason_phrase_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_json_path()) {
      json_path_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_text_location()) {
      if (text_location_ != NULL) text_location_->::pjcore::TextLocation::Clear();
    }
    if (has_cause()) {
      if (cause_ != NULL) cause_->::pjcore::Error::Clear();
    }
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  object_properties_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool Error::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pjcore.Error)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string description = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_description()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->description().data(), this->description().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "pjcore.Error.description");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_source_file;
        break;
      }

      // optional string source_file = 2;
      case 2: {
        if (tag == 18) {
         parse_source_file:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_source_file()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->source_file().data(), this->source_file().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "pjcore.Error.source_file");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_source_line;
        break;
      }

      // optional int32 source_line = 3;
      case 3: {
        if (tag == 24) {
         parse_source_line:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &source_line_)));
          set_has_source_line();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_system_errno;
        break;
      }

      // optional int32 system_errno = 4;
      case 4: {
        if (tag == 32) {
         parse_system_errno:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &system_errno_)));
          set_has_system_errno();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_system_errno_description;
        break;
      }

      // optional string system_errno_description = 5;
      case 5: {
        if (tag == 42) {
         parse_system_errno_description:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_system_errno_description()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->system_errno_description().data(), this->system_errno_description().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "pjcore.Error.system_errno_description");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(48)) goto parse_uv_errno;
        break;
      }

      // optional int32 uv_errno = 6;
      case 6: {
        if (tag == 48) {
         parse_uv_errno:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &uv_errno_)));
          set_has_uv_errno();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(58)) goto parse_uv_errno_description;
        break;
      }

      // optional string uv_errno_description = 7;
      case 7: {
        if (tag == 58) {
         parse_uv_errno_description:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_uv_errno_description()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->uv_errno_description().data(), this->uv_errno_description().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "pjcore.Error.uv_errno_description");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(64)) goto parse_http_errno;
        break;
      }

      // optional int32 http_errno = 8;
      case 8: {
        if (tag == 64) {
         parse_http_errno:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &http_errno_)));
          set_has_http_errno();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(74)) goto parse_http_errno_description;
        break;
      }

      // optional string http_errno_description = 9;
      case 9: {
        if (tag == 74) {
         parse_http_errno_description:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_http_errno_description()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->http_errno_description().data(), this->http_errno_description().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "pjcore.Error.http_errno_description");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(80)) goto parse_http_status_code;
        break;
      }

      // optional .pjcore.HttpStatusCode http_status_code = 10;
      case 10: {
        if (tag == 80) {
         parse_http_status_code:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::pjcore::HttpStatusCode_IsValid(value)) {
            set_http_status_code(static_cast< ::pjcore::HttpStatusCode >(value));
          } else {
            mutable_unknown_fields()->AddVarint(10, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(90)) goto parse_http_reason_phrase;
        break;
      }

      // optional string http_reason_phrase = 11;
      case 11: {
        if (tag == 90) {
         parse_http_reason_phrase:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_http_reason_phrase()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->http_reason_phrase().data(), this->http_reason_phrase().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "pjcore.Error.http_reason_phrase");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(98)) goto parse_json_path;
        break;
      }

      // optional string json_path = 12;
      case 12: {
        if (tag == 98) {
         parse_json_path:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_json_path()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->json_path().data(), this->json_path().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "pjcore.Error.json_path");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(106)) goto parse_text_location;
        break;
      }

      // optional .pjcore.TextLocation text_location = 13;
      case 13: {
        if (tag == 106) {
         parse_text_location:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_text_location()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(114)) goto parse_object_properties;
        break;
      }

      // repeated .pjcore.JsonValue.Property object_properties = 14;
      case 14: {
        if (tag == 114) {
         parse_object_properties:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_object_properties()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(114)) goto parse_object_properties;
        if (input->ExpectTag(122)) goto parse_cause;
        break;
      }

      // optional .pjcore.Error cause = 15;
      case 15: {
        if (tag == 122) {
         parse_cause:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_cause()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pjcore.Error)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pjcore.Error)
  return false;
#undef DO_
}

void Error::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pjcore.Error)
  // optional string description = 1;
  if (has_description()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->description().data(), this->description().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "pjcore.Error.description");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->description(), output);
  }

  // optional string source_file = 2;
  if (has_source_file()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->source_file().data(), this->source_file().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "pjcore.Error.source_file");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->source_file(), output);
  }

  // optional int32 source_line = 3;
  if (has_source_line()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->source_line(), output);
  }

  // optional int32 system_errno = 4;
  if (has_system_errno()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->system_errno(), output);
  }

  // optional string system_errno_description = 5;
  if (has_system_errno_description()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->system_errno_description().data(), this->system_errno_description().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "pjcore.Error.system_errno_description");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->system_errno_description(), output);
  }

  // optional int32 uv_errno = 6;
  if (has_uv_errno()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->uv_errno(), output);
  }

  // optional string uv_errno_description = 7;
  if (has_uv_errno_description()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->uv_errno_description().data(), this->uv_errno_description().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "pjcore.Error.uv_errno_description");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      7, this->uv_errno_description(), output);
  }

  // optional int32 http_errno = 8;
  if (has_http_errno()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(8, this->http_errno(), output);
  }

  // optional string http_errno_description = 9;
  if (has_http_errno_description()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->http_errno_description().data(), this->http_errno_description().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "pjcore.Error.http_errno_description");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      9, this->http_errno_description(), output);
  }

  // optional .pjcore.HttpStatusCode http_status_code = 10;
  if (has_http_status_code()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      10, this->http_status_code(), output);
  }

  // optional string http_reason_phrase = 11;
  if (has_http_reason_phrase()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->http_reason_phrase().data(), this->http_reason_phrase().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "pjcore.Error.http_reason_phrase");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      11, this->http_reason_phrase(), output);
  }

  // optional string json_path = 12;
  if (has_json_path()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->json_path().data(), this->json_path().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "pjcore.Error.json_path");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      12, this->json_path(), output);
  }

  // optional .pjcore.TextLocation text_location = 13;
  if (has_text_location()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      13, *this->text_location_, output);
  }

  // repeated .pjcore.JsonValue.Property object_properties = 14;
  for (unsigned int i = 0, n = this->object_properties_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      14, this->object_properties(i), output);
  }

  // optional .pjcore.Error cause = 15;
  if (has_cause()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      15, *this->cause_, output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:pjcore.Error)
}

::google::protobuf::uint8* Error::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:pjcore.Error)
  // optional string description = 1;
  if (has_description()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->description().data(), this->description().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "pjcore.Error.description");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->description(), target);
  }

  // optional string source_file = 2;
  if (has_source_file()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->source_file().data(), this->source_file().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "pjcore.Error.source_file");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->source_file(), target);
  }

  // optional int32 source_line = 3;
  if (has_source_line()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->source_line(), target);
  }

  // optional int32 system_errno = 4;
  if (has_system_errno()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->system_errno(), target);
  }

  // optional string system_errno_description = 5;
  if (has_system_errno_description()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->system_errno_description().data(), this->system_errno_description().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "pjcore.Error.system_errno_description");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->system_errno_description(), target);
  }

  // optional int32 uv_errno = 6;
  if (has_uv_errno()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(6, this->uv_errno(), target);
  }

  // optional string uv_errno_description = 7;
  if (has_uv_errno_description()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->uv_errno_description().data(), this->uv_errno_description().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "pjcore.Error.uv_errno_description");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        7, this->uv_errno_description(), target);
  }

  // optional int32 http_errno = 8;
  if (has_http_errno()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(8, this->http_errno(), target);
  }

  // optional string http_errno_description = 9;
  if (has_http_errno_description()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->http_errno_description().data(), this->http_errno_description().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "pjcore.Error.http_errno_description");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        9, this->http_errno_description(), target);
  }

  // optional .pjcore.HttpStatusCode http_status_code = 10;
  if (has_http_status_code()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      10, this->http_status_code(), target);
  }

  // optional string http_reason_phrase = 11;
  if (has_http_reason_phrase()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->http_reason_phrase().data(), this->http_reason_phrase().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "pjcore.Error.http_reason_phrase");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        11, this->http_reason_phrase(), target);
  }

  // optional string json_path = 12;
  if (has_json_path()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->json_path().data(), this->json_path().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "pjcore.Error.json_path");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        12, this->json_path(), target);
  }

  // optional .pjcore.TextLocation text_location = 13;
  if (has_text_location()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        13, *this->text_location_, target);
  }

  // repeated .pjcore.JsonValue.Property object_properties = 14;
  for (unsigned int i = 0, n = this->object_properties_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        14, this->object_properties(i), target);
  }

  // optional .pjcore.Error cause = 15;
  if (has_cause()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        15, *this->cause_, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pjcore.Error)
  return target;
}

int Error::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & 255) {
    // optional string description = 1;
    if (has_description()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->description());
    }

    // optional string source_file = 2;
    if (has_source_file()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->source_file());
    }

    // optional int32 source_line = 3;
    if (has_source_line()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->source_line());
    }

    // optional int32 system_errno = 4;
    if (has_system_errno()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->system_errno());
    }

    // optional string system_errno_description = 5;
    if (has_system_errno_description()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->system_errno_description());
    }

    // optional int32 uv_errno = 6;
    if (has_uv_errno()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->uv_errno());
    }

    // optional string uv_errno_description = 7;
    if (has_uv_errno_description()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->uv_errno_description());
    }

    // optional int32 http_errno = 8;
    if (has_http_errno()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->http_errno());
    }

  }
  if (_has_bits_[8 / 32] & 24320) {
    // optional string http_errno_description = 9;
    if (has_http_errno_description()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->http_errno_description());
    }

    // optional .pjcore.HttpStatusCode http_status_code = 10;
    if (has_http_status_code()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->http_status_code());
    }

    // optional string http_reason_phrase = 11;
    if (has_http_reason_phrase()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->http_reason_phrase());
    }

    // optional string json_path = 12;
    if (has_json_path()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->json_path());
    }

    // optional .pjcore.TextLocation text_location = 13;
    if (has_text_location()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->text_location_);
    }

    // optional .pjcore.Error cause = 15;
    if (has_cause()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->cause_);
    }

  }
  // repeated .pjcore.JsonValue.Property object_properties = 14;
  total_size += 1 * this->object_properties_size();
  for (int i = 0; i < this->object_properties_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->object_properties(i));
  }

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Error::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const Error* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Error*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Error::MergeFrom(const Error& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  object_properties_.MergeFrom(from.object_properties_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_description()) {
      set_has_description();
      description_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.description_);
    }
    if (from.has_source_file()) {
      set_has_source_file();
      source_file_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.source_file_);
    }
    if (from.has_source_line()) {
      set_source_line(from.source_line());
    }
    if (from.has_system_errno()) {
      set_system_errno(from.system_errno());
    }
    if (from.has_system_errno_description()) {
      set_has_system_errno_description();
      system_errno_description_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.system_errno_description_);
    }
    if (from.has_uv_errno()) {
      set_uv_errno(from.uv_errno());
    }
    if (from.has_uv_errno_description()) {
      set_has_uv_errno_description();
      uv_errno_description_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.uv_errno_description_);
    }
    if (from.has_http_errno()) {
      set_http_errno(from.http_errno());
    }
  }
  if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (from.has_http_errno_description()) {
      set_has_http_errno_description();
      http_errno_description_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.http_errno_description_);
    }
    if (from.has_http_status_code()) {
      set_http_status_code(from.http_status_code());
    }
    if (from.has_http_reason_phrase()) {
      set_has_http_reason_phrase();
      http_reason_phrase_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.http_reason_phrase_);
    }
    if (from.has_json_path()) {
      set_has_json_path();
      json_path_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.json_path_);
    }
    if (from.has_text_location()) {
      mutable_text_location()->::pjcore::TextLocation::MergeFrom(from.text_location());
    }
    if (from.has_cause()) {
      mutable_cause()->::pjcore::Error::MergeFrom(from.cause());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void Error::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Error::CopyFrom(const Error& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Error::IsInitialized() const {

  return true;
}

void Error::Swap(Error* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Error::InternalSwap(Error* other) {
  description_.Swap(&other->description_);
  source_file_.Swap(&other->source_file_);
  std::swap(source_line_, other->source_line_);
  std::swap(system_errno_, other->system_errno_);
  system_errno_description_.Swap(&other->system_errno_description_);
  std::swap(uv_errno_, other->uv_errno_);
  uv_errno_description_.Swap(&other->uv_errno_description_);
  std::swap(http_errno_, other->http_errno_);
  http_errno_description_.Swap(&other->http_errno_description_);
  std::swap(http_status_code_, other->http_status_code_);
  http_reason_phrase_.Swap(&other->http_reason_phrase_);
  json_path_.Swap(&other->json_path_);
  std::swap(text_location_, other->text_location_);
  object_properties_.UnsafeArenaSwap(&other->object_properties_);
  std::swap(cause_, other->cause_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Error::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Error_descriptor_;
  metadata.reflection = Error_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace pjcore

// @@protoc_insertion_point(global_scope)
