// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pjcore_test/test_message.proto

#ifndef PROTOBUF_pjcore_5ftest_2ftest_5fmessage_2eproto__INCLUDED
#define PROTOBUF_pjcore_5ftest_2ftest_5fmessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006002 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "pjcore/json.pb.h"
// @@protoc_insertion_point(includes)

namespace pjcore {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_pjcore_5ftest_2ftest_5fmessage_2eproto();
void protobuf_AssignDesc_pjcore_5ftest_2ftest_5fmessage_2eproto();
void protobuf_ShutdownFile_pjcore_5ftest_2ftest_5fmessage_2eproto();

class TestMessage;
class TestMessageWithObjectProperties;
class TestMessageWithStringMap;
class TestMessageWithStringMap_Entry;
class TestMessageWithIntMap;
class TestMessageWithIntMap_Entry;

enum TestMessage_TestEnum {
  TestMessage_TestEnum_TEST_ALPHA = 1,
  TestMessage_TestEnum_TEST_BETA = 2
};
bool TestMessage_TestEnum_IsValid(int value);
const TestMessage_TestEnum TestMessage_TestEnum_TestEnum_MIN = TestMessage_TestEnum_TEST_ALPHA;
const TestMessage_TestEnum TestMessage_TestEnum_TestEnum_MAX = TestMessage_TestEnum_TEST_BETA;
const int TestMessage_TestEnum_TestEnum_ARRAYSIZE = TestMessage_TestEnum_TestEnum_MAX + 1;

const ::google::protobuf::EnumDescriptor* TestMessage_TestEnum_descriptor();
inline const ::std::string& TestMessage_TestEnum_Name(TestMessage_TestEnum value) {
  return ::google::protobuf::internal::NameOfEnum(
    TestMessage_TestEnum_descriptor(), value);
}
inline bool TestMessage_TestEnum_Parse(
    const ::std::string& name, TestMessage_TestEnum* value) {
  return ::google::protobuf::internal::ParseNamedEnum<TestMessage_TestEnum>(
    TestMessage_TestEnum_descriptor(), name, value);
}
// ===================================================================

class TestMessage : public ::google::protobuf::Message {
 public:
  TestMessage();
  virtual ~TestMessage();

  TestMessage(const TestMessage& from);

  inline TestMessage& operator=(const TestMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TestMessage& default_instance();

  void Swap(TestMessage* other);

  // implements Message ----------------------------------------------

  inline TestMessage* New() const { return New(NULL); }

  TestMessage* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TestMessage& from);
  void MergeFrom(const TestMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(TestMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef TestMessage_TestEnum TestEnum;
  static const TestEnum TEST_ALPHA = TestMessage_TestEnum_TEST_ALPHA;
  static const TestEnum TEST_BETA = TestMessage_TestEnum_TEST_BETA;
  static inline bool TestEnum_IsValid(int value) {
    return TestMessage_TestEnum_IsValid(value);
  }
  static const TestEnum TestEnum_MIN =
    TestMessage_TestEnum_TestEnum_MIN;
  static const TestEnum TestEnum_MAX =
    TestMessage_TestEnum_TestEnum_MAX;
  static const int TestEnum_ARRAYSIZE =
    TestMessage_TestEnum_TestEnum_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  TestEnum_descriptor() {
    return TestMessage_TestEnum_descriptor();
  }
  static inline const ::std::string& TestEnum_Name(TestEnum value) {
    return TestMessage_TestEnum_Name(value);
  }
  static inline bool TestEnum_Parse(const ::std::string& name,
      TestEnum* value) {
    return TestMessage_TestEnum_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional int32 optional_int32 = 1;
  inline bool has_optional_int32() const;
  inline void clear_optional_int32();
  static const int kOptionalInt32FieldNumber = 1;
  inline ::google::protobuf::int32 optional_int32() const;
  inline void set_optional_int32(::google::protobuf::int32 value);

  // optional int64 optional_int64 = 2;
  inline bool has_optional_int64() const;
  inline void clear_optional_int64();
  static const int kOptionalInt64FieldNumber = 2;
  inline ::google::protobuf::int64 optional_int64() const;
  inline void set_optional_int64(::google::protobuf::int64 value);

  // optional uint32 optional_uint32 = 3;
  inline bool has_optional_uint32() const;
  inline void clear_optional_uint32();
  static const int kOptionalUint32FieldNumber = 3;
  inline ::google::protobuf::uint32 optional_uint32() const;
  inline void set_optional_uint32(::google::protobuf::uint32 value);

  // optional uint64 optional_uint64 = 4;
  inline bool has_optional_uint64() const;
  inline void clear_optional_uint64();
  static const int kOptionalUint64FieldNumber = 4;
  inline ::google::protobuf::uint64 optional_uint64() const;
  inline void set_optional_uint64(::google::protobuf::uint64 value);

  // optional double optional_double = 5;
  inline bool has_optional_double() const;
  inline void clear_optional_double();
  static const int kOptionalDoubleFieldNumber = 5;
  inline double optional_double() const;
  inline void set_optional_double(double value);

  // optional float optional_float = 6;
  inline bool has_optional_float() const;
  inline void clear_optional_float();
  static const int kOptionalFloatFieldNumber = 6;
  inline float optional_float() const;
  inline void set_optional_float(float value);

  // optional bool optional_bool = 7;
  inline bool has_optional_bool() const;
  inline void clear_optional_bool();
  static const int kOptionalBoolFieldNumber = 7;
  inline bool optional_bool() const;
  inline void set_optional_bool(bool value);

  // optional .pjcore.TestMessage.TestEnum optional_enum = 8;
  inline bool has_optional_enum() const;
  inline void clear_optional_enum();
  static const int kOptionalEnumFieldNumber = 8;
  inline ::pjcore::TestMessage_TestEnum optional_enum() const;
  inline void set_optional_enum(::pjcore::TestMessage_TestEnum value);

  // optional string optional_string = 9;
  inline bool has_optional_string() const;
  inline void clear_optional_string();
  static const int kOptionalStringFieldNumber = 9;
  inline const ::std::string& optional_string() const;
  inline void set_optional_string(const ::std::string& value);
  inline void set_optional_string(const char* value);
  inline void set_optional_string(const char* value, size_t size);
  inline ::std::string* mutable_optional_string();
  inline ::std::string* release_optional_string();
  inline void set_allocated_optional_string(::std::string* optional_string);

  // optional bytes optional_bytes = 10;
  inline bool has_optional_bytes() const;
  inline void clear_optional_bytes();
  static const int kOptionalBytesFieldNumber = 10;
  inline const ::std::string& optional_bytes() const;
  inline void set_optional_bytes(const ::std::string& value);
  inline void set_optional_bytes(const char* value);
  inline void set_optional_bytes(const void* value, size_t size);
  inline ::std::string* mutable_optional_bytes();
  inline ::std::string* release_optional_bytes();
  inline void set_allocated_optional_bytes(::std::string* optional_bytes);

  // optional .pjcore.TestMessage optional_message = 11;
  inline bool has_optional_message() const;
  inline void clear_optional_message();
  static const int kOptionalMessageFieldNumber = 11;
  inline const ::pjcore::TestMessage& optional_message() const;
  inline ::pjcore::TestMessage* mutable_optional_message();
  inline ::pjcore::TestMessage* release_optional_message();
  inline void set_allocated_optional_message(::pjcore::TestMessage* optional_message);

  // repeated int32 repeated_int32 = 101;
  inline int repeated_int32_size() const;
  inline void clear_repeated_int32();
  static const int kRepeatedInt32FieldNumber = 101;
  inline ::google::protobuf::int32 repeated_int32(int index) const;
  inline void set_repeated_int32(int index, ::google::protobuf::int32 value);
  inline void add_repeated_int32(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      repeated_int32() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_repeated_int32();

  // repeated int64 repeated_int64 = 102;
  inline int repeated_int64_size() const;
  inline void clear_repeated_int64();
  static const int kRepeatedInt64FieldNumber = 102;
  inline ::google::protobuf::int64 repeated_int64(int index) const;
  inline void set_repeated_int64(int index, ::google::protobuf::int64 value);
  inline void add_repeated_int64(::google::protobuf::int64 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      repeated_int64() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_repeated_int64();

  // repeated uint32 repeated_uint32 = 103;
  inline int repeated_uint32_size() const;
  inline void clear_repeated_uint32();
  static const int kRepeatedUint32FieldNumber = 103;
  inline ::google::protobuf::uint32 repeated_uint32(int index) const;
  inline void set_repeated_uint32(int index, ::google::protobuf::uint32 value);
  inline void add_repeated_uint32(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      repeated_uint32() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_repeated_uint32();

  // repeated uint64 repeated_uint64 = 104;
  inline int repeated_uint64_size() const;
  inline void clear_repeated_uint64();
  static const int kRepeatedUint64FieldNumber = 104;
  inline ::google::protobuf::uint64 repeated_uint64(int index) const;
  inline void set_repeated_uint64(int index, ::google::protobuf::uint64 value);
  inline void add_repeated_uint64(::google::protobuf::uint64 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      repeated_uint64() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_repeated_uint64();

  // repeated double repeated_double = 105;
  inline int repeated_double_size() const;
  inline void clear_repeated_double();
  static const int kRepeatedDoubleFieldNumber = 105;
  inline double repeated_double(int index) const;
  inline void set_repeated_double(int index, double value);
  inline void add_repeated_double(double value);
  inline const ::google::protobuf::RepeatedField< double >&
      repeated_double() const;
  inline ::google::protobuf::RepeatedField< double >*
      mutable_repeated_double();

  // repeated float repeated_float = 106;
  inline int repeated_float_size() const;
  inline void clear_repeated_float();
  static const int kRepeatedFloatFieldNumber = 106;
  inline float repeated_float(int index) const;
  inline void set_repeated_float(int index, float value);
  inline void add_repeated_float(float value);
  inline const ::google::protobuf::RepeatedField< float >&
      repeated_float() const;
  inline ::google::protobuf::RepeatedField< float >*
      mutable_repeated_float();

  // repeated bool repeated_bool = 107;
  inline int repeated_bool_size() const;
  inline void clear_repeated_bool();
  static const int kRepeatedBoolFieldNumber = 107;
  inline bool repeated_bool(int index) const;
  inline void set_repeated_bool(int index, bool value);
  inline void add_repeated_bool(bool value);
  inline const ::google::protobuf::RepeatedField< bool >&
      repeated_bool() const;
  inline ::google::protobuf::RepeatedField< bool >*
      mutable_repeated_bool();

  // repeated .pjcore.TestMessage.TestEnum repeated_enum = 108;
  inline int repeated_enum_size() const;
  inline void clear_repeated_enum();
  static const int kRepeatedEnumFieldNumber = 108;
  inline ::pjcore::TestMessage_TestEnum repeated_enum(int index) const;
  inline void set_repeated_enum(int index, ::pjcore::TestMessage_TestEnum value);
  inline void add_repeated_enum(::pjcore::TestMessage_TestEnum value);
  inline const ::google::protobuf::RepeatedField<int>& repeated_enum() const;
  inline ::google::protobuf::RepeatedField<int>* mutable_repeated_enum();

  // repeated string repeated_string = 109;
  inline int repeated_string_size() const;
  inline void clear_repeated_string();
  static const int kRepeatedStringFieldNumber = 109;
  inline const ::std::string& repeated_string(int index) const;
  inline ::std::string* mutable_repeated_string(int index);
  inline void set_repeated_string(int index, const ::std::string& value);
  inline void set_repeated_string(int index, const char* value);
  inline void set_repeated_string(int index, const char* value, size_t size);
  inline ::std::string* add_repeated_string();
  inline void add_repeated_string(const ::std::string& value);
  inline void add_repeated_string(const char* value);
  inline void add_repeated_string(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& repeated_string() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_repeated_string();

  // repeated bytes repeated_bytes = 110;
  inline int repeated_bytes_size() const;
  inline void clear_repeated_bytes();
  static const int kRepeatedBytesFieldNumber = 110;
  inline const ::std::string& repeated_bytes(int index) const;
  inline ::std::string* mutable_repeated_bytes(int index);
  inline void set_repeated_bytes(int index, const ::std::string& value);
  inline void set_repeated_bytes(int index, const char* value);
  inline void set_repeated_bytes(int index, const void* value, size_t size);
  inline ::std::string* add_repeated_bytes();
  inline void add_repeated_bytes(const ::std::string& value);
  inline void add_repeated_bytes(const char* value);
  inline void add_repeated_bytes(const void* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& repeated_bytes() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_repeated_bytes();

  // repeated .pjcore.TestMessage repeated_message = 111;
  inline int repeated_message_size() const;
  inline void clear_repeated_message();
  static const int kRepeatedMessageFieldNumber = 111;
  inline const ::pjcore::TestMessage& repeated_message(int index) const;
  inline ::pjcore::TestMessage* mutable_repeated_message(int index);
  inline ::pjcore::TestMessage* add_repeated_message();
  inline const ::google::protobuf::RepeatedPtrField< ::pjcore::TestMessage >&
      repeated_message() const;
  inline ::google::protobuf::RepeatedPtrField< ::pjcore::TestMessage >*
      mutable_repeated_message();

  // @@protoc_insertion_point(class_scope:pjcore.TestMessage)
 private:
  inline void set_has_optional_int32();
  inline void clear_has_optional_int32();
  inline void set_has_optional_int64();
  inline void clear_has_optional_int64();
  inline void set_has_optional_uint32();
  inline void clear_has_optional_uint32();
  inline void set_has_optional_uint64();
  inline void clear_has_optional_uint64();
  inline void set_has_optional_double();
  inline void clear_has_optional_double();
  inline void set_has_optional_float();
  inline void clear_has_optional_float();
  inline void set_has_optional_bool();
  inline void clear_has_optional_bool();
  inline void set_has_optional_enum();
  inline void clear_has_optional_enum();
  inline void set_has_optional_string();
  inline void clear_has_optional_string();
  inline void set_has_optional_bytes();
  inline void clear_has_optional_bytes();
  inline void set_has_optional_message();
  inline void clear_has_optional_message();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 optional_int64_;
  ::google::protobuf::int32 optional_int32_;
  ::google::protobuf::uint32 optional_uint32_;
  ::google::protobuf::uint64 optional_uint64_;
  double optional_double_;
  float optional_float_;
  bool optional_bool_;
  ::google::protobuf::internal::ArenaStringPtr optional_string_;
  ::google::protobuf::internal::ArenaStringPtr optional_bytes_;
  ::pjcore::TestMessage* optional_message_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > repeated_int32_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > repeated_int64_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > repeated_uint32_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > repeated_uint64_;
  ::google::protobuf::RepeatedField< double > repeated_double_;
  ::google::protobuf::RepeatedField< float > repeated_float_;
  ::google::protobuf::RepeatedField< bool > repeated_bool_;
  ::google::protobuf::RepeatedField<int> repeated_enum_;
  ::google::protobuf::RepeatedPtrField< ::std::string> repeated_string_;
  ::google::protobuf::RepeatedPtrField< ::std::string> repeated_bytes_;
  ::google::protobuf::RepeatedPtrField< ::pjcore::TestMessage > repeated_message_;
  int optional_enum_;
  friend void  protobuf_AddDesc_pjcore_5ftest_2ftest_5fmessage_2eproto();
  friend void protobuf_AssignDesc_pjcore_5ftest_2ftest_5fmessage_2eproto();
  friend void protobuf_ShutdownFile_pjcore_5ftest_2ftest_5fmessage_2eproto();

  void InitAsDefaultInstance();
  static TestMessage* default_instance_;
};
// -------------------------------------------------------------------

class TestMessageWithObjectProperties : public ::google::protobuf::Message {
 public:
  TestMessageWithObjectProperties();
  virtual ~TestMessageWithObjectProperties();

  TestMessageWithObjectProperties(const TestMessageWithObjectProperties& from);

  inline TestMessageWithObjectProperties& operator=(const TestMessageWithObjectProperties& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TestMessageWithObjectProperties& default_instance();

  void Swap(TestMessageWithObjectProperties* other);

  // implements Message ----------------------------------------------

  inline TestMessageWithObjectProperties* New() const { return New(NULL); }

  TestMessageWithObjectProperties* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TestMessageWithObjectProperties& from);
  void MergeFrom(const TestMessageWithObjectProperties& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(TestMessageWithObjectProperties* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .pjcore.JsonValue.Property object_properties = 201;
  inline int object_properties_size() const;
  inline void clear_object_properties();
  static const int kObjectPropertiesFieldNumber = 201;
  inline const ::pjcore::JsonValue_Property& object_properties(int index) const;
  inline ::pjcore::JsonValue_Property* mutable_object_properties(int index);
  inline ::pjcore::JsonValue_Property* add_object_properties();
  inline const ::google::protobuf::RepeatedPtrField< ::pjcore::JsonValue_Property >&
      object_properties() const;
  inline ::google::protobuf::RepeatedPtrField< ::pjcore::JsonValue_Property >*
      mutable_object_properties();

  // @@protoc_insertion_point(class_scope:pjcore.TestMessageWithObjectProperties)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::pjcore::JsonValue_Property > object_properties_;
  friend void  protobuf_AddDesc_pjcore_5ftest_2ftest_5fmessage_2eproto();
  friend void protobuf_AssignDesc_pjcore_5ftest_2ftest_5fmessage_2eproto();
  friend void protobuf_ShutdownFile_pjcore_5ftest_2ftest_5fmessage_2eproto();

  void InitAsDefaultInstance();
  static TestMessageWithObjectProperties* default_instance_;
};
// -------------------------------------------------------------------

class TestMessageWithStringMap_Entry : public ::google::protobuf::Message {
 public:
  TestMessageWithStringMap_Entry();
  virtual ~TestMessageWithStringMap_Entry();

  TestMessageWithStringMap_Entry(const TestMessageWithStringMap_Entry& from);

  inline TestMessageWithStringMap_Entry& operator=(const TestMessageWithStringMap_Entry& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TestMessageWithStringMap_Entry& default_instance();

  void Swap(TestMessageWithStringMap_Entry* other);

  // implements Message ----------------------------------------------

  inline TestMessageWithStringMap_Entry* New() const { return New(NULL); }

  TestMessageWithStringMap_Entry* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TestMessageWithStringMap_Entry& from);
  void MergeFrom(const TestMessageWithStringMap_Entry& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(TestMessageWithStringMap_Entry* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // optional int32 data = 2;
  inline bool has_data() const;
  inline void clear_data();
  static const int kDataFieldNumber = 2;
  inline ::google::protobuf::int32 data() const;
  inline void set_data(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:pjcore.TestMessageWithStringMap.Entry)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_data();
  inline void clear_has_data();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::int32 data_;
  friend void  protobuf_AddDesc_pjcore_5ftest_2ftest_5fmessage_2eproto();
  friend void protobuf_AssignDesc_pjcore_5ftest_2ftest_5fmessage_2eproto();
  friend void protobuf_ShutdownFile_pjcore_5ftest_2ftest_5fmessage_2eproto();

  void InitAsDefaultInstance();
  static TestMessageWithStringMap_Entry* default_instance_;
};
// -------------------------------------------------------------------

class TestMessageWithStringMap : public ::google::protobuf::Message {
 public:
  TestMessageWithStringMap();
  virtual ~TestMessageWithStringMap();

  TestMessageWithStringMap(const TestMessageWithStringMap& from);

  inline TestMessageWithStringMap& operator=(const TestMessageWithStringMap& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TestMessageWithStringMap& default_instance();

  void Swap(TestMessageWithStringMap* other);

  // implements Message ----------------------------------------------

  inline TestMessageWithStringMap* New() const { return New(NULL); }

  TestMessageWithStringMap* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TestMessageWithStringMap& from);
  void MergeFrom(const TestMessageWithStringMap& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(TestMessageWithStringMap* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef TestMessageWithStringMap_Entry Entry;

  // accessors -------------------------------------------------------

  // repeated .pjcore.TestMessageWithStringMap.Entry entries = 1;
  inline int entries_size() const;
  inline void clear_entries();
  static const int kEntriesFieldNumber = 1;
  inline const ::pjcore::TestMessageWithStringMap_Entry& entries(int index) const;
  inline ::pjcore::TestMessageWithStringMap_Entry* mutable_entries(int index);
  inline ::pjcore::TestMessageWithStringMap_Entry* add_entries();
  inline const ::google::protobuf::RepeatedPtrField< ::pjcore::TestMessageWithStringMap_Entry >&
      entries() const;
  inline ::google::protobuf::RepeatedPtrField< ::pjcore::TestMessageWithStringMap_Entry >*
      mutable_entries();

  // @@protoc_insertion_point(class_scope:pjcore.TestMessageWithStringMap)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::pjcore::TestMessageWithStringMap_Entry > entries_;
  friend void  protobuf_AddDesc_pjcore_5ftest_2ftest_5fmessage_2eproto();
  friend void protobuf_AssignDesc_pjcore_5ftest_2ftest_5fmessage_2eproto();
  friend void protobuf_ShutdownFile_pjcore_5ftest_2ftest_5fmessage_2eproto();

  void InitAsDefaultInstance();
  static TestMessageWithStringMap* default_instance_;
};
// -------------------------------------------------------------------

class TestMessageWithIntMap_Entry : public ::google::protobuf::Message {
 public:
  TestMessageWithIntMap_Entry();
  virtual ~TestMessageWithIntMap_Entry();

  TestMessageWithIntMap_Entry(const TestMessageWithIntMap_Entry& from);

  inline TestMessageWithIntMap_Entry& operator=(const TestMessageWithIntMap_Entry& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TestMessageWithIntMap_Entry& default_instance();

  void Swap(TestMessageWithIntMap_Entry* other);

  // implements Message ----------------------------------------------

  inline TestMessageWithIntMap_Entry* New() const { return New(NULL); }

  TestMessageWithIntMap_Entry* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TestMessageWithIntMap_Entry& from);
  void MergeFrom(const TestMessageWithIntMap_Entry& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(TestMessageWithIntMap_Entry* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline ::google::protobuf::int32 name() const;
  inline void set_name(::google::protobuf::int32 value);

  // optional string data = 2;
  inline bool has_data() const;
  inline void clear_data();
  static const int kDataFieldNumber = 2;
  inline const ::std::string& data() const;
  inline void set_data(const ::std::string& value);
  inline void set_data(const char* value);
  inline void set_data(const char* value, size_t size);
  inline ::std::string* mutable_data();
  inline ::std::string* release_data();
  inline void set_allocated_data(::std::string* data);

  // @@protoc_insertion_point(class_scope:pjcore.TestMessageWithIntMap.Entry)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_data();
  inline void clear_has_data();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr data_;
  ::google::protobuf::int32 name_;
  friend void  protobuf_AddDesc_pjcore_5ftest_2ftest_5fmessage_2eproto();
  friend void protobuf_AssignDesc_pjcore_5ftest_2ftest_5fmessage_2eproto();
  friend void protobuf_ShutdownFile_pjcore_5ftest_2ftest_5fmessage_2eproto();

  void InitAsDefaultInstance();
  static TestMessageWithIntMap_Entry* default_instance_;
};
// -------------------------------------------------------------------

class TestMessageWithIntMap : public ::google::protobuf::Message {
 public:
  TestMessageWithIntMap();
  virtual ~TestMessageWithIntMap();

  TestMessageWithIntMap(const TestMessageWithIntMap& from);

  inline TestMessageWithIntMap& operator=(const TestMessageWithIntMap& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TestMessageWithIntMap& default_instance();

  void Swap(TestMessageWithIntMap* other);

  // implements Message ----------------------------------------------

  inline TestMessageWithIntMap* New() const { return New(NULL); }

  TestMessageWithIntMap* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TestMessageWithIntMap& from);
  void MergeFrom(const TestMessageWithIntMap& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(TestMessageWithIntMap* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef TestMessageWithIntMap_Entry Entry;

  // accessors -------------------------------------------------------

  // repeated .pjcore.TestMessageWithIntMap.Entry entries = 1;
  inline int entries_size() const;
  inline void clear_entries();
  static const int kEntriesFieldNumber = 1;
  inline const ::pjcore::TestMessageWithIntMap_Entry& entries(int index) const;
  inline ::pjcore::TestMessageWithIntMap_Entry* mutable_entries(int index);
  inline ::pjcore::TestMessageWithIntMap_Entry* add_entries();
  inline const ::google::protobuf::RepeatedPtrField< ::pjcore::TestMessageWithIntMap_Entry >&
      entries() const;
  inline ::google::protobuf::RepeatedPtrField< ::pjcore::TestMessageWithIntMap_Entry >*
      mutable_entries();

  // @@protoc_insertion_point(class_scope:pjcore.TestMessageWithIntMap)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::pjcore::TestMessageWithIntMap_Entry > entries_;
  friend void  protobuf_AddDesc_pjcore_5ftest_2ftest_5fmessage_2eproto();
  friend void protobuf_AssignDesc_pjcore_5ftest_2ftest_5fmessage_2eproto();
  friend void protobuf_ShutdownFile_pjcore_5ftest_2ftest_5fmessage_2eproto();

  void InitAsDefaultInstance();
  static TestMessageWithIntMap* default_instance_;
};
// ===================================================================


// ===================================================================

// TestMessage

// optional int32 optional_int32 = 1;
inline bool TestMessage::has_optional_int32() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TestMessage::set_has_optional_int32() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TestMessage::clear_has_optional_int32() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TestMessage::clear_optional_int32() {
  optional_int32_ = 0;
  clear_has_optional_int32();
}
inline ::google::protobuf::int32 TestMessage::optional_int32() const {
  // @@protoc_insertion_point(field_get:pjcore.TestMessage.optional_int32)
  return optional_int32_;
}
inline void TestMessage::set_optional_int32(::google::protobuf::int32 value) {
  set_has_optional_int32();
  optional_int32_ = value;
  // @@protoc_insertion_point(field_set:pjcore.TestMessage.optional_int32)
}

// optional int64 optional_int64 = 2;
inline bool TestMessage::has_optional_int64() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TestMessage::set_has_optional_int64() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TestMessage::clear_has_optional_int64() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TestMessage::clear_optional_int64() {
  optional_int64_ = GOOGLE_LONGLONG(0);
  clear_has_optional_int64();
}
inline ::google::protobuf::int64 TestMessage::optional_int64() const {
  // @@protoc_insertion_point(field_get:pjcore.TestMessage.optional_int64)
  return optional_int64_;
}
inline void TestMessage::set_optional_int64(::google::protobuf::int64 value) {
  set_has_optional_int64();
  optional_int64_ = value;
  // @@protoc_insertion_point(field_set:pjcore.TestMessage.optional_int64)
}

// optional uint32 optional_uint32 = 3;
inline bool TestMessage::has_optional_uint32() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void TestMessage::set_has_optional_uint32() {
  _has_bits_[0] |= 0x00000004u;
}
inline void TestMessage::clear_has_optional_uint32() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void TestMessage::clear_optional_uint32() {
  optional_uint32_ = 0u;
  clear_has_optional_uint32();
}
inline ::google::protobuf::uint32 TestMessage::optional_uint32() const {
  // @@protoc_insertion_point(field_get:pjcore.TestMessage.optional_uint32)
  return optional_uint32_;
}
inline void TestMessage::set_optional_uint32(::google::protobuf::uint32 value) {
  set_has_optional_uint32();
  optional_uint32_ = value;
  // @@protoc_insertion_point(field_set:pjcore.TestMessage.optional_uint32)
}

// optional uint64 optional_uint64 = 4;
inline bool TestMessage::has_optional_uint64() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void TestMessage::set_has_optional_uint64() {
  _has_bits_[0] |= 0x00000008u;
}
inline void TestMessage::clear_has_optional_uint64() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void TestMessage::clear_optional_uint64() {
  optional_uint64_ = GOOGLE_ULONGLONG(0);
  clear_has_optional_uint64();
}
inline ::google::protobuf::uint64 TestMessage::optional_uint64() const {
  // @@protoc_insertion_point(field_get:pjcore.TestMessage.optional_uint64)
  return optional_uint64_;
}
inline void TestMessage::set_optional_uint64(::google::protobuf::uint64 value) {
  set_has_optional_uint64();
  optional_uint64_ = value;
  // @@protoc_insertion_point(field_set:pjcore.TestMessage.optional_uint64)
}

// optional double optional_double = 5;
inline bool TestMessage::has_optional_double() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void TestMessage::set_has_optional_double() {
  _has_bits_[0] |= 0x00000010u;
}
inline void TestMessage::clear_has_optional_double() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void TestMessage::clear_optional_double() {
  optional_double_ = 0;
  clear_has_optional_double();
}
inline double TestMessage::optional_double() const {
  // @@protoc_insertion_point(field_get:pjcore.TestMessage.optional_double)
  return optional_double_;
}
inline void TestMessage::set_optional_double(double value) {
  set_has_optional_double();
  optional_double_ = value;
  // @@protoc_insertion_point(field_set:pjcore.TestMessage.optional_double)
}

// optional float optional_float = 6;
inline bool TestMessage::has_optional_float() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void TestMessage::set_has_optional_float() {
  _has_bits_[0] |= 0x00000020u;
}
inline void TestMessage::clear_has_optional_float() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void TestMessage::clear_optional_float() {
  optional_float_ = 0;
  clear_has_optional_float();
}
inline float TestMessage::optional_float() const {
  // @@protoc_insertion_point(field_get:pjcore.TestMessage.optional_float)
  return optional_float_;
}
inline void TestMessage::set_optional_float(float value) {
  set_has_optional_float();
  optional_float_ = value;
  // @@protoc_insertion_point(field_set:pjcore.TestMessage.optional_float)
}

// optional bool optional_bool = 7;
inline bool TestMessage::has_optional_bool() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void TestMessage::set_has_optional_bool() {
  _has_bits_[0] |= 0x00000040u;
}
inline void TestMessage::clear_has_optional_bool() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void TestMessage::clear_optional_bool() {
  optional_bool_ = false;
  clear_has_optional_bool();
}
inline bool TestMessage::optional_bool() const {
  // @@protoc_insertion_point(field_get:pjcore.TestMessage.optional_bool)
  return optional_bool_;
}
inline void TestMessage::set_optional_bool(bool value) {
  set_has_optional_bool();
  optional_bool_ = value;
  // @@protoc_insertion_point(field_set:pjcore.TestMessage.optional_bool)
}

// optional .pjcore.TestMessage.TestEnum optional_enum = 8;
inline bool TestMessage::has_optional_enum() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void TestMessage::set_has_optional_enum() {
  _has_bits_[0] |= 0x00000080u;
}
inline void TestMessage::clear_has_optional_enum() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void TestMessage::clear_optional_enum() {
  optional_enum_ = 1;
  clear_has_optional_enum();
}
inline ::pjcore::TestMessage_TestEnum TestMessage::optional_enum() const {
  // @@protoc_insertion_point(field_get:pjcore.TestMessage.optional_enum)
  return static_cast< ::pjcore::TestMessage_TestEnum >(optional_enum_);
}
inline void TestMessage::set_optional_enum(::pjcore::TestMessage_TestEnum value) {
  assert(::pjcore::TestMessage_TestEnum_IsValid(value));
  set_has_optional_enum();
  optional_enum_ = value;
  // @@protoc_insertion_point(field_set:pjcore.TestMessage.optional_enum)
}

// optional string optional_string = 9;
inline bool TestMessage::has_optional_string() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void TestMessage::set_has_optional_string() {
  _has_bits_[0] |= 0x00000100u;
}
inline void TestMessage::clear_has_optional_string() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void TestMessage::clear_optional_string() {
  optional_string_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_optional_string();
}
inline const ::std::string& TestMessage::optional_string() const {
  // @@protoc_insertion_point(field_get:pjcore.TestMessage.optional_string)
  return optional_string_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TestMessage::set_optional_string(const ::std::string& value) {
  set_has_optional_string();
  optional_string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pjcore.TestMessage.optional_string)
}
inline void TestMessage::set_optional_string(const char* value) {
  set_has_optional_string();
  optional_string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pjcore.TestMessage.optional_string)
}
inline void TestMessage::set_optional_string(const char* value, size_t size) {
  set_has_optional_string();
  optional_string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pjcore.TestMessage.optional_string)
}
inline ::std::string* TestMessage::mutable_optional_string() {
  set_has_optional_string();
  // @@protoc_insertion_point(field_mutable:pjcore.TestMessage.optional_string)
  return optional_string_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TestMessage::release_optional_string() {
  clear_has_optional_string();
  return optional_string_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TestMessage::set_allocated_optional_string(::std::string* optional_string) {
  if (optional_string != NULL) {
    set_has_optional_string();
  } else {
    clear_has_optional_string();
  }
  optional_string_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), optional_string);
  // @@protoc_insertion_point(field_set_allocated:pjcore.TestMessage.optional_string)
}

// optional bytes optional_bytes = 10;
inline bool TestMessage::has_optional_bytes() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void TestMessage::set_has_optional_bytes() {
  _has_bits_[0] |= 0x00000200u;
}
inline void TestMessage::clear_has_optional_bytes() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void TestMessage::clear_optional_bytes() {
  optional_bytes_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_optional_bytes();
}
inline const ::std::string& TestMessage::optional_bytes() const {
  // @@protoc_insertion_point(field_get:pjcore.TestMessage.optional_bytes)
  return optional_bytes_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TestMessage::set_optional_bytes(const ::std::string& value) {
  set_has_optional_bytes();
  optional_bytes_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pjcore.TestMessage.optional_bytes)
}
inline void TestMessage::set_optional_bytes(const char* value) {
  set_has_optional_bytes();
  optional_bytes_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pjcore.TestMessage.optional_bytes)
}
inline void TestMessage::set_optional_bytes(const void* value, size_t size) {
  set_has_optional_bytes();
  optional_bytes_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pjcore.TestMessage.optional_bytes)
}
inline ::std::string* TestMessage::mutable_optional_bytes() {
  set_has_optional_bytes();
  // @@protoc_insertion_point(field_mutable:pjcore.TestMessage.optional_bytes)
  return optional_bytes_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TestMessage::release_optional_bytes() {
  clear_has_optional_bytes();
  return optional_bytes_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TestMessage::set_allocated_optional_bytes(::std::string* optional_bytes) {
  if (optional_bytes != NULL) {
    set_has_optional_bytes();
  } else {
    clear_has_optional_bytes();
  }
  optional_bytes_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), optional_bytes);
  // @@protoc_insertion_point(field_set_allocated:pjcore.TestMessage.optional_bytes)
}

// optional .pjcore.TestMessage optional_message = 11;
inline bool TestMessage::has_optional_message() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void TestMessage::set_has_optional_message() {
  _has_bits_[0] |= 0x00000400u;
}
inline void TestMessage::clear_has_optional_message() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void TestMessage::clear_optional_message() {
  if (optional_message_ != NULL) optional_message_->::pjcore::TestMessage::Clear();
  clear_has_optional_message();
}
inline const ::pjcore::TestMessage& TestMessage::optional_message() const {
  // @@protoc_insertion_point(field_get:pjcore.TestMessage.optional_message)
  return optional_message_ != NULL ? *optional_message_ : *default_instance_->optional_message_;
}
inline ::pjcore::TestMessage* TestMessage::mutable_optional_message() {
  set_has_optional_message();
  if (optional_message_ == NULL) {
    optional_message_ = new ::pjcore::TestMessage;
  }
  // @@protoc_insertion_point(field_mutable:pjcore.TestMessage.optional_message)
  return optional_message_;
}
inline ::pjcore::TestMessage* TestMessage::release_optional_message() {
  clear_has_optional_message();
  ::pjcore::TestMessage* temp = optional_message_;
  optional_message_ = NULL;
  return temp;
}
inline void TestMessage::set_allocated_optional_message(::pjcore::TestMessage* optional_message) {
  delete optional_message_;
  optional_message_ = optional_message;
  if (optional_message) {
    set_has_optional_message();
  } else {
    clear_has_optional_message();
  }
  // @@protoc_insertion_point(field_set_allocated:pjcore.TestMessage.optional_message)
}

// repeated int32 repeated_int32 = 101;
inline int TestMessage::repeated_int32_size() const {
  return repeated_int32_.size();
}
inline void TestMessage::clear_repeated_int32() {
  repeated_int32_.Clear();
}
inline ::google::protobuf::int32 TestMessage::repeated_int32(int index) const {
  // @@protoc_insertion_point(field_get:pjcore.TestMessage.repeated_int32)
  return repeated_int32_.Get(index);
}
inline void TestMessage::set_repeated_int32(int index, ::google::protobuf::int32 value) {
  repeated_int32_.Set(index, value);
  // @@protoc_insertion_point(field_set:pjcore.TestMessage.repeated_int32)
}
inline void TestMessage::add_repeated_int32(::google::protobuf::int32 value) {
  repeated_int32_.Add(value);
  // @@protoc_insertion_point(field_add:pjcore.TestMessage.repeated_int32)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
TestMessage::repeated_int32() const {
  // @@protoc_insertion_point(field_list:pjcore.TestMessage.repeated_int32)
  return repeated_int32_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
TestMessage::mutable_repeated_int32() {
  // @@protoc_insertion_point(field_mutable_list:pjcore.TestMessage.repeated_int32)
  return &repeated_int32_;
}

// repeated int64 repeated_int64 = 102;
inline int TestMessage::repeated_int64_size() const {
  return repeated_int64_.size();
}
inline void TestMessage::clear_repeated_int64() {
  repeated_int64_.Clear();
}
inline ::google::protobuf::int64 TestMessage::repeated_int64(int index) const {
  // @@protoc_insertion_point(field_get:pjcore.TestMessage.repeated_int64)
  return repeated_int64_.Get(index);
}
inline void TestMessage::set_repeated_int64(int index, ::google::protobuf::int64 value) {
  repeated_int64_.Set(index, value);
  // @@protoc_insertion_point(field_set:pjcore.TestMessage.repeated_int64)
}
inline void TestMessage::add_repeated_int64(::google::protobuf::int64 value) {
  repeated_int64_.Add(value);
  // @@protoc_insertion_point(field_add:pjcore.TestMessage.repeated_int64)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
TestMessage::repeated_int64() const {
  // @@protoc_insertion_point(field_list:pjcore.TestMessage.repeated_int64)
  return repeated_int64_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
TestMessage::mutable_repeated_int64() {
  // @@protoc_insertion_point(field_mutable_list:pjcore.TestMessage.repeated_int64)
  return &repeated_int64_;
}

// repeated uint32 repeated_uint32 = 103;
inline int TestMessage::repeated_uint32_size() const {
  return repeated_uint32_.size();
}
inline void TestMessage::clear_repeated_uint32() {
  repeated_uint32_.Clear();
}
inline ::google::protobuf::uint32 TestMessage::repeated_uint32(int index) const {
  // @@protoc_insertion_point(field_get:pjcore.TestMessage.repeated_uint32)
  return repeated_uint32_.Get(index);
}
inline void TestMessage::set_repeated_uint32(int index, ::google::protobuf::uint32 value) {
  repeated_uint32_.Set(index, value);
  // @@protoc_insertion_point(field_set:pjcore.TestMessage.repeated_uint32)
}
inline void TestMessage::add_repeated_uint32(::google::protobuf::uint32 value) {
  repeated_uint32_.Add(value);
  // @@protoc_insertion_point(field_add:pjcore.TestMessage.repeated_uint32)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
TestMessage::repeated_uint32() const {
  // @@protoc_insertion_point(field_list:pjcore.TestMessage.repeated_uint32)
  return repeated_uint32_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
TestMessage::mutable_repeated_uint32() {
  // @@protoc_insertion_point(field_mutable_list:pjcore.TestMessage.repeated_uint32)
  return &repeated_uint32_;
}

// repeated uint64 repeated_uint64 = 104;
inline int TestMessage::repeated_uint64_size() const {
  return repeated_uint64_.size();
}
inline void TestMessage::clear_repeated_uint64() {
  repeated_uint64_.Clear();
}
inline ::google::protobuf::uint64 TestMessage::repeated_uint64(int index) const {
  // @@protoc_insertion_point(field_get:pjcore.TestMessage.repeated_uint64)
  return repeated_uint64_.Get(index);
}
inline void TestMessage::set_repeated_uint64(int index, ::google::protobuf::uint64 value) {
  repeated_uint64_.Set(index, value);
  // @@protoc_insertion_point(field_set:pjcore.TestMessage.repeated_uint64)
}
inline void TestMessage::add_repeated_uint64(::google::protobuf::uint64 value) {
  repeated_uint64_.Add(value);
  // @@protoc_insertion_point(field_add:pjcore.TestMessage.repeated_uint64)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
TestMessage::repeated_uint64() const {
  // @@protoc_insertion_point(field_list:pjcore.TestMessage.repeated_uint64)
  return repeated_uint64_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
TestMessage::mutable_repeated_uint64() {
  // @@protoc_insertion_point(field_mutable_list:pjcore.TestMessage.repeated_uint64)
  return &repeated_uint64_;
}

// repeated double repeated_double = 105;
inline int TestMessage::repeated_double_size() const {
  return repeated_double_.size();
}
inline void TestMessage::clear_repeated_double() {
  repeated_double_.Clear();
}
inline double TestMessage::repeated_double(int index) const {
  // @@protoc_insertion_point(field_get:pjcore.TestMessage.repeated_double)
  return repeated_double_.Get(index);
}
inline void TestMessage::set_repeated_double(int index, double value) {
  repeated_double_.Set(index, value);
  // @@protoc_insertion_point(field_set:pjcore.TestMessage.repeated_double)
}
inline void TestMessage::add_repeated_double(double value) {
  repeated_double_.Add(value);
  // @@protoc_insertion_point(field_add:pjcore.TestMessage.repeated_double)
}
inline const ::google::protobuf::RepeatedField< double >&
TestMessage::repeated_double() const {
  // @@protoc_insertion_point(field_list:pjcore.TestMessage.repeated_double)
  return repeated_double_;
}
inline ::google::protobuf::RepeatedField< double >*
TestMessage::mutable_repeated_double() {
  // @@protoc_insertion_point(field_mutable_list:pjcore.TestMessage.repeated_double)
  return &repeated_double_;
}

// repeated float repeated_float = 106;
inline int TestMessage::repeated_float_size() const {
  return repeated_float_.size();
}
inline void TestMessage::clear_repeated_float() {
  repeated_float_.Clear();
}
inline float TestMessage::repeated_float(int index) const {
  // @@protoc_insertion_point(field_get:pjcore.TestMessage.repeated_float)
  return repeated_float_.Get(index);
}
inline void TestMessage::set_repeated_float(int index, float value) {
  repeated_float_.Set(index, value);
  // @@protoc_insertion_point(field_set:pjcore.TestMessage.repeated_float)
}
inline void TestMessage::add_repeated_float(float value) {
  repeated_float_.Add(value);
  // @@protoc_insertion_point(field_add:pjcore.TestMessage.repeated_float)
}
inline const ::google::protobuf::RepeatedField< float >&
TestMessage::repeated_float() const {
  // @@protoc_insertion_point(field_list:pjcore.TestMessage.repeated_float)
  return repeated_float_;
}
inline ::google::protobuf::RepeatedField< float >*
TestMessage::mutable_repeated_float() {
  // @@protoc_insertion_point(field_mutable_list:pjcore.TestMessage.repeated_float)
  return &repeated_float_;
}

// repeated bool repeated_bool = 107;
inline int TestMessage::repeated_bool_size() const {
  return repeated_bool_.size();
}
inline void TestMessage::clear_repeated_bool() {
  repeated_bool_.Clear();
}
inline bool TestMessage::repeated_bool(int index) const {
  // @@protoc_insertion_point(field_get:pjcore.TestMessage.repeated_bool)
  return repeated_bool_.Get(index);
}
inline void TestMessage::set_repeated_bool(int index, bool value) {
  repeated_bool_.Set(index, value);
  // @@protoc_insertion_point(field_set:pjcore.TestMessage.repeated_bool)
}
inline void TestMessage::add_repeated_bool(bool value) {
  repeated_bool_.Add(value);
  // @@protoc_insertion_point(field_add:pjcore.TestMessage.repeated_bool)
}
inline const ::google::protobuf::RepeatedField< bool >&
TestMessage::repeated_bool() const {
  // @@protoc_insertion_point(field_list:pjcore.TestMessage.repeated_bool)
  return repeated_bool_;
}
inline ::google::protobuf::RepeatedField< bool >*
TestMessage::mutable_repeated_bool() {
  // @@protoc_insertion_point(field_mutable_list:pjcore.TestMessage.repeated_bool)
  return &repeated_bool_;
}

// repeated .pjcore.TestMessage.TestEnum repeated_enum = 108;
inline int TestMessage::repeated_enum_size() const {
  return repeated_enum_.size();
}
inline void TestMessage::clear_repeated_enum() {
  repeated_enum_.Clear();
}
inline ::pjcore::TestMessage_TestEnum TestMessage::repeated_enum(int index) const {
  // @@protoc_insertion_point(field_get:pjcore.TestMessage.repeated_enum)
  return static_cast< ::pjcore::TestMessage_TestEnum >(repeated_enum_.Get(index));
}
inline void TestMessage::set_repeated_enum(int index, ::pjcore::TestMessage_TestEnum value) {
  assert(::pjcore::TestMessage_TestEnum_IsValid(value));
  repeated_enum_.Set(index, value);
  // @@protoc_insertion_point(field_set:pjcore.TestMessage.repeated_enum)
}
inline void TestMessage::add_repeated_enum(::pjcore::TestMessage_TestEnum value) {
  assert(::pjcore::TestMessage_TestEnum_IsValid(value));
  repeated_enum_.Add(value);
  // @@protoc_insertion_point(field_add:pjcore.TestMessage.repeated_enum)
}
inline const ::google::protobuf::RepeatedField<int>&
TestMessage::repeated_enum() const {
  // @@protoc_insertion_point(field_list:pjcore.TestMessage.repeated_enum)
  return repeated_enum_;
}
inline ::google::protobuf::RepeatedField<int>*
TestMessage::mutable_repeated_enum() {
  // @@protoc_insertion_point(field_mutable_list:pjcore.TestMessage.repeated_enum)
  return &repeated_enum_;
}

// repeated string repeated_string = 109;
inline int TestMessage::repeated_string_size() const {
  return repeated_string_.size();
}
inline void TestMessage::clear_repeated_string() {
  repeated_string_.Clear();
}
inline const ::std::string& TestMessage::repeated_string(int index) const {
  // @@protoc_insertion_point(field_get:pjcore.TestMessage.repeated_string)
  return repeated_string_.Get(index);
}
inline ::std::string* TestMessage::mutable_repeated_string(int index) {
  // @@protoc_insertion_point(field_mutable:pjcore.TestMessage.repeated_string)
  return repeated_string_.Mutable(index);
}
inline void TestMessage::set_repeated_string(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:pjcore.TestMessage.repeated_string)
  repeated_string_.Mutable(index)->assign(value);
}
inline void TestMessage::set_repeated_string(int index, const char* value) {
  repeated_string_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:pjcore.TestMessage.repeated_string)
}
inline void TestMessage::set_repeated_string(int index, const char* value, size_t size) {
  repeated_string_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:pjcore.TestMessage.repeated_string)
}
inline ::std::string* TestMessage::add_repeated_string() {
  return repeated_string_.Add();
}
inline void TestMessage::add_repeated_string(const ::std::string& value) {
  repeated_string_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:pjcore.TestMessage.repeated_string)
}
inline void TestMessage::add_repeated_string(const char* value) {
  repeated_string_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:pjcore.TestMessage.repeated_string)
}
inline void TestMessage::add_repeated_string(const char* value, size_t size) {
  repeated_string_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:pjcore.TestMessage.repeated_string)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
TestMessage::repeated_string() const {
  // @@protoc_insertion_point(field_list:pjcore.TestMessage.repeated_string)
  return repeated_string_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
TestMessage::mutable_repeated_string() {
  // @@protoc_insertion_point(field_mutable_list:pjcore.TestMessage.repeated_string)
  return &repeated_string_;
}

// repeated bytes repeated_bytes = 110;
inline int TestMessage::repeated_bytes_size() const {
  return repeated_bytes_.size();
}
inline void TestMessage::clear_repeated_bytes() {
  repeated_bytes_.Clear();
}
inline const ::std::string& TestMessage::repeated_bytes(int index) const {
  // @@protoc_insertion_point(field_get:pjcore.TestMessage.repeated_bytes)
  return repeated_bytes_.Get(index);
}
inline ::std::string* TestMessage::mutable_repeated_bytes(int index) {
  // @@protoc_insertion_point(field_mutable:pjcore.TestMessage.repeated_bytes)
  return repeated_bytes_.Mutable(index);
}
inline void TestMessage::set_repeated_bytes(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:pjcore.TestMessage.repeated_bytes)
  repeated_bytes_.Mutable(index)->assign(value);
}
inline void TestMessage::set_repeated_bytes(int index, const char* value) {
  repeated_bytes_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:pjcore.TestMessage.repeated_bytes)
}
inline void TestMessage::set_repeated_bytes(int index, const void* value, size_t size) {
  repeated_bytes_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:pjcore.TestMessage.repeated_bytes)
}
inline ::std::string* TestMessage::add_repeated_bytes() {
  return repeated_bytes_.Add();
}
inline void TestMessage::add_repeated_bytes(const ::std::string& value) {
  repeated_bytes_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:pjcore.TestMessage.repeated_bytes)
}
inline void TestMessage::add_repeated_bytes(const char* value) {
  repeated_bytes_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:pjcore.TestMessage.repeated_bytes)
}
inline void TestMessage::add_repeated_bytes(const void* value, size_t size) {
  repeated_bytes_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:pjcore.TestMessage.repeated_bytes)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
TestMessage::repeated_bytes() const {
  // @@protoc_insertion_point(field_list:pjcore.TestMessage.repeated_bytes)
  return repeated_bytes_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
TestMessage::mutable_repeated_bytes() {
  // @@protoc_insertion_point(field_mutable_list:pjcore.TestMessage.repeated_bytes)
  return &repeated_bytes_;
}

// repeated .pjcore.TestMessage repeated_message = 111;
inline int TestMessage::repeated_message_size() const {
  return repeated_message_.size();
}
inline void TestMessage::clear_repeated_message() {
  repeated_message_.Clear();
}
inline const ::pjcore::TestMessage& TestMessage::repeated_message(int index) const {
  // @@protoc_insertion_point(field_get:pjcore.TestMessage.repeated_message)
  return repeated_message_.Get(index);
}
inline ::pjcore::TestMessage* TestMessage::mutable_repeated_message(int index) {
  // @@protoc_insertion_point(field_mutable:pjcore.TestMessage.repeated_message)
  return repeated_message_.Mutable(index);
}
inline ::pjcore::TestMessage* TestMessage::add_repeated_message() {
  // @@protoc_insertion_point(field_add:pjcore.TestMessage.repeated_message)
  return repeated_message_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::pjcore::TestMessage >&
TestMessage::repeated_message() const {
  // @@protoc_insertion_point(field_list:pjcore.TestMessage.repeated_message)
  return repeated_message_;
}
inline ::google::protobuf::RepeatedPtrField< ::pjcore::TestMessage >*
TestMessage::mutable_repeated_message() {
  // @@protoc_insertion_point(field_mutable_list:pjcore.TestMessage.repeated_message)
  return &repeated_message_;
}

// -------------------------------------------------------------------

// TestMessageWithObjectProperties

// repeated .pjcore.JsonValue.Property object_properties = 201;
inline int TestMessageWithObjectProperties::object_properties_size() const {
  return object_properties_.size();
}
inline void TestMessageWithObjectProperties::clear_object_properties() {
  object_properties_.Clear();
}
inline const ::pjcore::JsonValue_Property& TestMessageWithObjectProperties::object_properties(int index) const {
  // @@protoc_insertion_point(field_get:pjcore.TestMessageWithObjectProperties.object_properties)
  return object_properties_.Get(index);
}
inline ::pjcore::JsonValue_Property* TestMessageWithObjectProperties::mutable_object_properties(int index) {
  // @@protoc_insertion_point(field_mutable:pjcore.TestMessageWithObjectProperties.object_properties)
  return object_properties_.Mutable(index);
}
inline ::pjcore::JsonValue_Property* TestMessageWithObjectProperties::add_object_properties() {
  // @@protoc_insertion_point(field_add:pjcore.TestMessageWithObjectProperties.object_properties)
  return object_properties_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::pjcore::JsonValue_Property >&
TestMessageWithObjectProperties::object_properties() const {
  // @@protoc_insertion_point(field_list:pjcore.TestMessageWithObjectProperties.object_properties)
  return object_properties_;
}
inline ::google::protobuf::RepeatedPtrField< ::pjcore::JsonValue_Property >*
TestMessageWithObjectProperties::mutable_object_properties() {
  // @@protoc_insertion_point(field_mutable_list:pjcore.TestMessageWithObjectProperties.object_properties)
  return &object_properties_;
}

// -------------------------------------------------------------------

// TestMessageWithStringMap_Entry

// optional string name = 1;
inline bool TestMessageWithStringMap_Entry::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TestMessageWithStringMap_Entry::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TestMessageWithStringMap_Entry::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TestMessageWithStringMap_Entry::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& TestMessageWithStringMap_Entry::name() const {
  // @@protoc_insertion_point(field_get:pjcore.TestMessageWithStringMap.Entry.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TestMessageWithStringMap_Entry::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pjcore.TestMessageWithStringMap.Entry.name)
}
inline void TestMessageWithStringMap_Entry::set_name(const char* value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pjcore.TestMessageWithStringMap.Entry.name)
}
inline void TestMessageWithStringMap_Entry::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pjcore.TestMessageWithStringMap.Entry.name)
}
inline ::std::string* TestMessageWithStringMap_Entry::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:pjcore.TestMessageWithStringMap.Entry.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TestMessageWithStringMap_Entry::release_name() {
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TestMessageWithStringMap_Entry::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:pjcore.TestMessageWithStringMap.Entry.name)
}

// optional int32 data = 2;
inline bool TestMessageWithStringMap_Entry::has_data() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TestMessageWithStringMap_Entry::set_has_data() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TestMessageWithStringMap_Entry::clear_has_data() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TestMessageWithStringMap_Entry::clear_data() {
  data_ = 0;
  clear_has_data();
}
inline ::google::protobuf::int32 TestMessageWithStringMap_Entry::data() const {
  // @@protoc_insertion_point(field_get:pjcore.TestMessageWithStringMap.Entry.data)
  return data_;
}
inline void TestMessageWithStringMap_Entry::set_data(::google::protobuf::int32 value) {
  set_has_data();
  data_ = value;
  // @@protoc_insertion_point(field_set:pjcore.TestMessageWithStringMap.Entry.data)
}

// -------------------------------------------------------------------

// TestMessageWithStringMap

// repeated .pjcore.TestMessageWithStringMap.Entry entries = 1;
inline int TestMessageWithStringMap::entries_size() const {
  return entries_.size();
}
inline void TestMessageWithStringMap::clear_entries() {
  entries_.Clear();
}
inline const ::pjcore::TestMessageWithStringMap_Entry& TestMessageWithStringMap::entries(int index) const {
  // @@protoc_insertion_point(field_get:pjcore.TestMessageWithStringMap.entries)
  return entries_.Get(index);
}
inline ::pjcore::TestMessageWithStringMap_Entry* TestMessageWithStringMap::mutable_entries(int index) {
  // @@protoc_insertion_point(field_mutable:pjcore.TestMessageWithStringMap.entries)
  return entries_.Mutable(index);
}
inline ::pjcore::TestMessageWithStringMap_Entry* TestMessageWithStringMap::add_entries() {
  // @@protoc_insertion_point(field_add:pjcore.TestMessageWithStringMap.entries)
  return entries_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::pjcore::TestMessageWithStringMap_Entry >&
TestMessageWithStringMap::entries() const {
  // @@protoc_insertion_point(field_list:pjcore.TestMessageWithStringMap.entries)
  return entries_;
}
inline ::google::protobuf::RepeatedPtrField< ::pjcore::TestMessageWithStringMap_Entry >*
TestMessageWithStringMap::mutable_entries() {
  // @@protoc_insertion_point(field_mutable_list:pjcore.TestMessageWithStringMap.entries)
  return &entries_;
}

// -------------------------------------------------------------------

// TestMessageWithIntMap_Entry

// optional int32 name = 1;
inline bool TestMessageWithIntMap_Entry::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TestMessageWithIntMap_Entry::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TestMessageWithIntMap_Entry::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TestMessageWithIntMap_Entry::clear_name() {
  name_ = 0;
  clear_has_name();
}
inline ::google::protobuf::int32 TestMessageWithIntMap_Entry::name() const {
  // @@protoc_insertion_point(field_get:pjcore.TestMessageWithIntMap.Entry.name)
  return name_;
}
inline void TestMessageWithIntMap_Entry::set_name(::google::protobuf::int32 value) {
  set_has_name();
  name_ = value;
  // @@protoc_insertion_point(field_set:pjcore.TestMessageWithIntMap.Entry.name)
}

// optional string data = 2;
inline bool TestMessageWithIntMap_Entry::has_data() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TestMessageWithIntMap_Entry::set_has_data() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TestMessageWithIntMap_Entry::clear_has_data() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TestMessageWithIntMap_Entry::clear_data() {
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_data();
}
inline const ::std::string& TestMessageWithIntMap_Entry::data() const {
  // @@protoc_insertion_point(field_get:pjcore.TestMessageWithIntMap.Entry.data)
  return data_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TestMessageWithIntMap_Entry::set_data(const ::std::string& value) {
  set_has_data();
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pjcore.TestMessageWithIntMap.Entry.data)
}
inline void TestMessageWithIntMap_Entry::set_data(const char* value) {
  set_has_data();
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pjcore.TestMessageWithIntMap.Entry.data)
}
inline void TestMessageWithIntMap_Entry::set_data(const char* value, size_t size) {
  set_has_data();
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pjcore.TestMessageWithIntMap.Entry.data)
}
inline ::std::string* TestMessageWithIntMap_Entry::mutable_data() {
  set_has_data();
  // @@protoc_insertion_point(field_mutable:pjcore.TestMessageWithIntMap.Entry.data)
  return data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TestMessageWithIntMap_Entry::release_data() {
  clear_has_data();
  return data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TestMessageWithIntMap_Entry::set_allocated_data(::std::string* data) {
  if (data != NULL) {
    set_has_data();
  } else {
    clear_has_data();
  }
  data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data);
  // @@protoc_insertion_point(field_set_allocated:pjcore.TestMessageWithIntMap.Entry.data)
}

// -------------------------------------------------------------------

// TestMessageWithIntMap

// repeated .pjcore.TestMessageWithIntMap.Entry entries = 1;
inline int TestMessageWithIntMap::entries_size() const {
  return entries_.size();
}
inline void TestMessageWithIntMap::clear_entries() {
  entries_.Clear();
}
inline const ::pjcore::TestMessageWithIntMap_Entry& TestMessageWithIntMap::entries(int index) const {
  // @@protoc_insertion_point(field_get:pjcore.TestMessageWithIntMap.entries)
  return entries_.Get(index);
}
inline ::pjcore::TestMessageWithIntMap_Entry* TestMessageWithIntMap::mutable_entries(int index) {
  // @@protoc_insertion_point(field_mutable:pjcore.TestMessageWithIntMap.entries)
  return entries_.Mutable(index);
}
inline ::pjcore::TestMessageWithIntMap_Entry* TestMessageWithIntMap::add_entries() {
  // @@protoc_insertion_point(field_add:pjcore.TestMessageWithIntMap.entries)
  return entries_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::pjcore::TestMessageWithIntMap_Entry >&
TestMessageWithIntMap::entries() const {
  // @@protoc_insertion_point(field_list:pjcore.TestMessageWithIntMap.entries)
  return entries_;
}
inline ::google::protobuf::RepeatedPtrField< ::pjcore::TestMessageWithIntMap_Entry >*
TestMessageWithIntMap::mutable_entries() {
  // @@protoc_insertion_point(field_mutable_list:pjcore.TestMessageWithIntMap.entries)
  return &entries_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace pjcore

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::pjcore::TestMessage_TestEnum> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::pjcore::TestMessage_TestEnum>() {
  return ::pjcore::TestMessage_TestEnum_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_pjcore_5ftest_2ftest_5fmessage_2eproto__INCLUDED
